### ISSUE TITLE
cloud_provider value for unsupported CSP

### ISSUE THREAD

**Issue by anweiss** [hyperledger-labs/blockchain-automation-framework#1001]
I'd like to test the use of the BAF with Hyperledger Fabric on an IBM Cloud Kubernetes Cluster (IKS). However, the `cloud_provider` property in network.yaml only supports one of `aws`, `azure`, `gcp` or `minikube`. Is it possible to deploy BAF with Fabric to IKS if I leave this value blank?

**Comment by sownak** [comment]
you can define a new value for `cloud_provider` for IBM, and then you will have to update the code for the required storage class, and any other changes needed to support IBM Kubernetes cluster.

**Comment by jagpreetsinghsasan** [comment]
You can refer to our operational guide on how to add a new storage class
https://blockchain-automation-framework.readthedocs.io/en/latest/operations/adding_new_storageclass.html

**Comment by jagpreetsinghsasan** [comment]
@anweiss Are you currently working on this? If you can contribute this feature to BAF, it would be appreciated.

**Comment by anweiss** [comment]
Thanks @jagpreetsinghsasan, I'm still trying to wrap my head around making the necessary changes so I can deploy to IKS. I might have some additional questions.

**Comment by suvajit-sarkar** [comment]
Can you please contribute the cloud_provider code for IKS to BAF?

**Comment by anweiss** [comment]
Sure thing @suvajit-sarkar. Will push soon.

**Comment by sownak** [comment]
@anweiss Are you progressing on this? Otherwise we will be closing the issue as `wontfix`

**Comment by sownak** [comment]
Closing this issue as it is stale.

**Comment by uqix** [comment]
Tips about adding cloud_provider for private k8s.

Notes:

* replace coollu with private or something, it's just a enum value
* we use plain k8s sc, adjust as needed

```
3 files changed, 10 insertions(+), 1 deletion(-)
.../roles/create/storageclass/templates/coollu_sc.tpl              | 7 +++++++
.../configuration/roles/create/storageclass/vars/main.yaml         | 2 ++
platforms/network-schema.json                                      | 2 +-

new file   platforms/hyperledger-fabric/configuration/roles/create/storageclass/templates/coollu_sc.tpl
@@ -0,0 +1,7 @@
+apiVersion: storage.k8s.io/v1
+kind: StorageClass
+metadata:
+  name: {{ sc_name }}
+provisioner: kubernetes.io/no-provisioner
+volumeBindingMode: WaitForFirstConsumer
+reclaimPolicy: Retain

modified   platforms/hyperledger-fabric/configuration/roles/create/storageclass/vars/main.yaml
@@ -15,3 +15,5 @@ sc_templates:
   digitalocean-peer: digitalocean_sc.tpl
   oke-orderer: oke_sc.tpl
   oke-peer: oke_sc.tpl
+  coollu-orderer: coollu_sc.tpl
+  coollu-peer: coollu_sc.tpl

modified   platforms/network-schema.json
@@ -185,7 +185,7 @@
             "k8s":{ "$ref":"#/definitions/shared_k8s"},
             "vault":{ "$ref":"#/definitions/shared_vault"},
             "gitops":{ "$ref":"#/definitions/shared_gitops"},
-            "cloud_provider":{ "type": "string","enum": ["aws","aws-baremetal", "azure","gcp","minikube"]},
+            "cloud_provider":{ "type": "string","enum": ["aws","aws-baremetal", "azure","gcp","minikube","coollu"]},
             "gcp":{},
             "azure":{},
             "minikube":{},
```
