### ISSUE TITLE
Add a new validator organization in existing besu network.

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1017]
### Description
As a developer I want to add new validator organization in existing besu network. Add a validator nodes using `ibft_proposeValidatorVote` api method.

1) Refer to the [documentation](https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/IBFT/#adding-and-removing-validators) for adding a validator peer.
2) Perform the mannual addition of a new validator node in besu on baf network
3) Add the required changes in ansible for generating the crypto material for new validator organization.
4) add the new node to an existing besu network using ansible.
5) Update the `samples/network.yaml`
6) Update the readme and operational guide.

### Acceptance Criteria

1. Ansible playbook to add a new node to the existing network
2. use the curl command to get the peer count and number of validators. 
       `curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' http://carrierl.rc.dev2.aws.blockchaincloudpoc-develop.com:15011`
       `curl -X POST --data '{"jsonrpc":"2.0","method":"ibft_getValidatorsByBlockNumber","params":["latest"], "id":1}' http://carrierl.rc.dev2.aws.blockchaincloudpoc-develop.com:15011`
3. create furthur stories if required.

**Comment by ragalz** [comment]
I'll take on this one

**Comment by jagpreetsinghsasan** [comment]
For reference: #1276
