### ISSUE TITLE
Upgrade BAF docker build to install and use JAVA version 14 and 8

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1023]
### Description
As a developer I want to use BAF docker build with different tags having JAVA version 14 and JAVA 8 

### Acceptance Criteria
1. BAF docker build installs and uses specific java version as default
3. Update the BAF build docker image file with a different tag.

**Comment by vincentmele** [comment]
Why Java 14? The current Corda [documentation ](https://docs.corda.net/docs/corda-os/4.6/getting-set-up.html#installing-the-java-8-jdk)(Corda 4.6) specifically states Corda only supports Java 8 and not Java 9+. Whether or not Corda works with Java 14 is a different question, and even if it does, if this change was made it seems like it would introduce a significant risk of making Corda behave unpredictably and in an unsupported manner.

**Comment by pppazos** [comment]
Images created in development instance:
REPOSITORY                                                              TAG                         IMAGE ID           
hyperledgerlabs/baf-build                                               jdk8                        67cb6aa71857        
hyperledgerlabs/baf-build                                               jdk14                       52878ac12f31       

jdk8:
- upgraded base to ubuntu 20:4
- upgraded minor version in python to 3.6.13
- openjdk 8

jdk14:
- upgraded base to ubuntu 20:4
- upgraded minor version in python to 3.6.13
- openjdk 14
