### ISSUE TITLE
Setting up hlf on AKS 

### ISSUE THREAD

**Issue by pikvik** [hyperledger-labs/blockchain-automation-framework#1047]
I have AKS cluster , wish to deploy all the services of fabric network . According to the provided docs/video (youtube) we are using ansible and pointing to host configuration file.

We want to use kube config and kubectl api to talk to cluster instead of directly using kubernetes node in host config file (hard coded ip addresses) 

Please assist with this approach !!

**Comment by jagpreetsinghsasan** [comment]
Blockchain Automation Framework (or BAF) also follows a similar approach on setting up fabric network. Please refer to our [docs ](https://blockchain-automation-framework.readthedocs.io/en/latest/index.html) for the same

For queries, use our [rocket chat](https://chat.hyperledger.org/channel/blockchain-automation-framework).

I will close this issue as the 'enhancement' tag is used to have feature requests to BAF and your mentioned requirements are already satisfied with BAF
