### ISSUE TITLE
Fabric reset network is failing

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#1057]
**Describe the bug**
Fabric reset network is failing with following error
TASK [include_role : delete/genesis] *******************************************
fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'channels'"}

PLAY RECAP *********************************************************************
localhost                  : ok=257  changed=95   unreachable=0    failed=1    skipped=292  rescued=0    ignored=1 

**To Reproduce**
1. Run reset network on Fabric
2. See error as mentioned above

**Expected behavior**
Reset should be successful.

**Comment by abevers** [comment]
I'll take a look, never had the issue before running PR. The role should loop over the channels in the `network.yaml`, I'm sure you have those as well, right?

**Comment by sownak** [comment]
No, the application does not have channels. Please raise a PR for baf-configurations to fix this issue.

**Comment by abevers** [comment]
**RCA** 
The `delete/genesis` task loops over the `channels` parameter in the `network.yaml`. As the application does not have any channels, it throws an error.

**Comment by abevers** [comment]
@sownak I assume this issue is for both application deployments (Raft and Kafka?)

**Comment by abevers** [comment]
After discussing with @jagpreetsinghsasan and @suvajit-sarkar, for now I will patch the bug by adding an empty `channels` block to the `network.yaml`s for the application code. I will research a better way to do this (a check for the empty/missing variable for example).

**Comment by sownak** [comment]
This does not fix the issue!

**Comment by abevers** [comment]
Which is what I suspected. Researching a fix for this now, using [this link](https://stackoverflow.com/questions/60725648/ansible-how-to-skip-the-loop-if-the-list-is-empty) as a baseline. This should skip the tasks if the list is empty/not iterable.

**Comment by abevers** [comment]
@sownak  I have a possible fix as below:
```
# Delete genesis
- include_role:
   name: "delete/genesis"
   loop: "{{ network['channels'] }}"
   when: "network['channels'] is defined and (network['channels']|length>0)"
```
What I'd like to know from you: once you delete the `channel` key again, it only failed on the reset playbook, correct? 
The deploy playbook worked fine without any channels. If so, then this fix should be enough.

**Comment by sownak** [comment]
Then the check is not needed.

**Comment by abevers** [comment]
For the `delete/genesis` role, the loop is not needed. I removed the loop in the `reset-network.yaml` in PR #1069 and will revert the playbook change on the `baf-configuration` repo.
