### ISSUE TITLE
Add the anchor peer support for the addition of new peer in fabric.

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1058]
### Description
As a developer I want to add a new peer to an organization in an running fabric network, as an anchor peer.

1. go through the [link](https://hyperledger-fabric.readthedocs.io/en/release-1.4/channel_update_tutorial.html#updating-the-channel-config-to-include-an-org3-anchor-peer-optional) from the fabric docs.
2. create a script simmilar to `platforms\hyperledger-fabric\configuration\roles\create\new_organization\create_block` to add the anchor peer information of the new peer added to the organization.
3. use `jq` to append the json object with the anchor information for the new peer `jq '.channel_group.groups.Application.groups.clMSP.values.AnchorPeers.value.anchor_peers[1] |= . + {"host": "newpeer.org3.example.com","port": 11051}' config.json > newconfig.json`
3. Use the existing role `platforms\hyperledger-fabric\configuration\roles\setup\config_block`  to run the script to fetch and modify the config block.
4. Use the role `platforms\hyperledger-fabric\configuration\roles\setup\config_block\sign_and_update` to get the block signed and update the config block.

### Acceptance Criteria
1. Anchor peer information of new peer to be added to the channel
2. Tested on fabric 1.4.4 and 2.2.0

**Comment by suvajit-sarkar** [comment]
Needed to tested to confirm if this is fixed

**Comment by alvaropicazo** [comment]
Deployed an scenario with one peer organization (calv, which is the creator) with only one anchor peer (peer0). After the deployment, I wanted to add a new anchor peer for this org to this network (peer1). After the add-peer playbook terminated, I checked if the peer was successfully added:
![1_addpeer](https://user-images.githubusercontent.com/76157062/115423659-4e28e480-a1fe-11eb-931f-47b3647389cf.png)
