### ISSUE TITLE
Update couchDB images from fabric-couchdb:0.4.14 to couchdb:3.1.0 for HL Fabric v2.2.0

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1088]
### Description
As a developer I want to upgrade the couchDB version (and if required the charts) for HLFabric platform to support the recommended standalone version 3.1.0

Currently in BAF, couchDB uses the image hyperledger/faric-couchdb:0.4.14. This needs to be upgraded to couchdb:3.1.0
For more information refer to [HL Fabric v2.2.0 changelog](https://github.com/hyperledger/fabric/releases/tag/v2.2.0)

### Acceptance Criteria

- [x] Upgrade the couchdb image versions
- [x] Update the charts to incorporate changes if any
- [x] Network should be tested from end to end alongside adding of new organization

**Comment by rahultoraskarr** [comment]
I would like to work on this

**Comment by rahultoraskarr** [comment]
Note: Change the couchdb image tag to 'couchdb:3.1.1'. Refer https://github.com/hyperledger/fabric-samples/blob/master/test-network/docker/docker-compose-couch.yaml.
