### ISSUE TITLE
Removal of an organization from a running HL Fabric network deployed using BAF

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1101]
### Description
As a developer I want to remove organization from a running HL Fabric network, deployed using BAF.
This will most probably use the existing channel block edition code (used in add a new org) along with more features

### Relevant Link
https://medium.com/@kctheservant/remove-an-organization-from-a-running-fabric-network-55f52cd0a012

### Acceptance Criteria
1. Existing org can be removed from a running network
2. The block hash for channel should match to the one before the org is added (to check)
3. Crypto should be removed from the vault for the decommissioned organization
4. Kubernetes resources for the decommissioned organization should be removed

**Comment by rahultoraskarr** [comment]
I am interested to work in this issue.
