### ISSUE TITLE
Corda expresseapi deployment fails

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#1103]
**Describe the bug**
Corda supplychain API deployment fails.
Logs from helmrelease describe
Events:
  Type     Reason             Age                 From           Message
  ----     ------             ----                ----           -------
  Warning  FailedReleaseSync  87s (x21 over 23m)  helm-operator  synchronization of release 'manufacturercorda-expressapi' in namespace 'manufacturer-ns' failed: installation failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec.selector.matchLabels): invalid type for io.k8s.api.core.v1.ServiceSpec.selector: got "map", expected "string"

**To Reproduce**
1. Deploy supplychain app on Corda opensource after the network is running.
2. manufacturer-expressapi pod does not start

**Expected behavior**
All expressapi pods should start.

**Environment (please complete the following information):**
 - Helm version 3
 - Version: Corda Opensource

**Comment by jagpreetsinghsasan** [comment]
This bug came because of #1099 
Reverted the changes to fix this
