### ISSUE TITLE
Upgrade chaincode playbook is not working for Fabric 2.2 code

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1109]
**Describe the bug**
Upgrade chaincode playbook execution fails with error `'dict object' has no attribute language`  when running for the fabric 2.2.

<img width="458" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/56861637/96109578-6725a580-0efc-11eb-86b7-38db873b9ac7.png">

**To Reproduce**
1. Edit network.yaml for fabric version 2.2
2. Setup the network
3. Try to run uprade chaincode playbook

**Expected behavior**
Java chaincode should be upgraded using the upgrade chaincode playbook.

**Comment by suvajit-sarkar** [comment]
this issue will be solved by the feature #1133

**Comment by lakshyakumar** [comment]
RCA: The java chaincode support was not added to the upgrade chaincode in fabric version 2.2. The upgrading of  `go` and `java` chaincode for fabric version 2.2 is supported using the `chaincode-install-instantiate.yaml` playbook.
