### ISSUE TITLE
Correct the fabric pod and job checks and incorporate retry count in the code

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#112]
### Description
Some of the checks in fabric are on services, instead of pod checks.. need to fix those checks

**Comment by jagpreetsinghsasan** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/56861721/69318028-490ae300-0c62-11ea-8f32-090a2151e16c.png)

**Comment by suvajit-sarkar** [comment]
Closing : Merged PR #114
