### ISSUE TITLE
Update the R3 Corda Enterprise images to the right versions & naming schemes

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1123]
### Description
**As a** developer, **I want to** update the R3 Corda Enterprise images to the right versions & naming schemes, **so that** you can easily deploy multiple versions of the CENM and Nodes.

Currently, the CENM Notary docker image uses the 1.2 tag as it's baseline, as seen in the code snippet below:
https://github.com/hyperledger-labs/blockchain-automation-framework/blob/f48d1a3070f082feb1fd918df1130d11dd853e53/platforms/r3-corda-ent/images/notary.dockerfile#L1

This tag has to be updated to the `4.4-zulu-openjdk8u242` as per [this reference link](https://hub.docker.com/r/corda/enterprise-notary/tags).
Accordingly, update deployment file creation logic to include this version in the  `main.yaml` for `notary` & `notary-initial-registration`.

Additionally, update the `/platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml` to include logic to use multiple versions. 

### Acceptance Criteria
1. Update internal BAF repository with the updated tag for the `notary` image 
2. Multiple versions of images can be supported by changing the versions in the network.yaml
3. Test the BAF deployment by deploying CENM + nodes and verifying the nodes are registered by using the `/network-map-user/node-infos` API endpoint

**Comment by abevers** [comment]
To support multiple versions of images, the `org.type = node` also needs a `version` tag, like the `org.type: cenm` has. I'll raise a PR to baf-configuration for this.

**Comment by abevers** [comment]
Verified the network deployment by using the `network-map-user/node-infos` endpoint:
![image](https://user-images.githubusercontent.com/67095118/97599080-e9878c80-1a07-11eb-97bb-03ea790aa3a5.png)
