### ISSUE TITLE
Manually test Corda Enterprise Firewall and Float in separate cluster

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1136]
### Description
As a developer I want to Corda Enterprise Firewall and Float in separate cluster test so that automation of the same can be achieved

### Acceptance Criteria
1. Deploy Corda enterprise network using BAF and manually test integration of float running on different cluster
2. Create stories based on the outcome to automate the deployment

**Comment by jagpreetsinghsasan** [comment]
Created stories #1149 #1150
