### ISSUE TITLE
Option to change the 'eks_worker_sg' inbound source IP for ports 30000-32767

### ISSUE THREAD

**Issue by jwavoetacn** [hyperledger-labs/blockchain-automation-framework#1151]
**Is your feature request related to a problem? Please describe.**
This feature request as about an option to change the inbound source IP for the **'eks_worker_sg'** Security Groups configured in Helm using the ports **30000-32767** . By not being in control of this source IP a potential security risk is created as discovered by our companies security team.

**Describe the solution you'd like**
I would like to have the option to change the inbound source IP to either a range or specific IP. This way the Security Group is more secure by limiting the inbound connections.

**Describe alternatives you've considered**
I tried to change the rules manually within the AWS console. Unfortunately AWS EKS 'detects' these changes and will not remove/updates these rules anymore. This eventually results in the rule limit being reached causing AWS EKS being unable to add new rules.   

**Additional context**

Screenshot of the Security Groups with the rules containing the 0.0.0.0/0 IP we want to change:
![image](https://user-images.githubusercontent.com/68590662/98101588-ba06d300-1e92-11eb-87b5-c9d218faf942.png)

**Comment by jwavoetacn** [comment]
Files to change:
- shared/charts/ambassador/templates/service.yaml ->add 'loadBalancerSourceRanges'
- shared/charts/ambassador/values.yaml -> add variable (for example: 'loadBalancerSourceRanges:')
- shared/configuration/roles/setup/ambassador/task/main.yaml -> line 52 -> --set ambassador.loadBalancerSourceRanges={{ network.env.loadBalancerSourceRanges }}

**Comment by jwavoetacn** [comment]
Added the following lines to the ./ambassador/templates/service.yaml:
![image](https://user-images.githubusercontent.com/68590662/99952424-f174eb00-2d7f-11eb-8206-d8848d5752d6.png)

Added the 'loadBalancerSourceRanges' value to ./ambassador/values.yaml:
![image](https://user-images.githubusercontent.com/68590662/99952450-fc2f8000-2d7f-11eb-924b-4588431e4301.png)

Added '--set ambassador.loadBalancerSourceRanges={{ network.env.loadBalancerSourceRanges }}' to 'KUBECONFIG=' in the ./ambassador/tasks/main.yaml on line 52:
![image](https://user-images.githubusercontent.com/68590662/99952503-0cdff600-2d80-11eb-9ee0-e01ac52fecd1.png)

Added 'loadBalancerSourceRanges:' to the network-cordav2.yaml:
![image](https://user-images.githubusercontent.com/68590662/99952528-15d0c780-2d80-11eb-83e4-8f03e2087781.png)

These changes make it possible to add custom IPs to the inbound rules for the ports in the range: 30000-32767

**Comment by suvajit-sarkar** [comment]
Reopening
