### ISSUE TITLE
The postman collection suite is not working for supplychain Ref App on fabric version 2.2

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1156]
**Describe the bug**
The postman collection suite is not working for fabric version 2.2, the same chaincode function from the peer cli as 
`peer chaincode invoke -o ${ORDERER_URL} --tls --cafile ${ORDERER_CA} -C ${CHANNEL_NAME} -n supplychain --peerAddresses <peer0-cl-Address> --peerAddresses <peer0-ml-Address> --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/crypto/endorsers/cl/msp/cacerts/ca.crt --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/crypto/endorsers/ml/msp/cacerts/ca.crt -c '{"function":"createContainer","Args":["{\"misc\":{\"name\":\"Medicine Container\"},\"trackingID\":\"613254c0-5395-4069-971b-fff77dc9c73d\",\"counterparties\":[\"CN=Admin@org2.example.com,OU=client+OU=org2,O=Org2,L=San Francisco,C=US\"]}"]}'`  is working. We found out that the syntax of the invokation is different from the non-lifecycle enabled chaincode. Investigate and fix the same

**To Reproduce**
1. Edit fabric network.yaml for version fabric 2.2
2. Setup the fabric networ version 2.2
3. Setup the ref app.
4. run create container api from postman.

**Expected behavior**
The postman api collection suite should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/56861637/98355092-b10b3280-2047-11eb-8f65-9ddafafffef6.png)

**Comment by suvajit-sarkar** [comment]
Dependent on #1147

**Comment by jagpreetsinghsasan** [comment]
For fabric 2.2, the node sdk is changed, as per the [documentation](https://hyperledger.github.io/fabric-sdk-node/)
This folder needs to be looked into
https://github.com/hyperledger-labs/blockchain-automation-framework/tree/develop/examples/supplychain-app/fabric/chaincode_rest_server/rest-server/src

**Comment by lakshyakumar** [comment]
The postman api calls are working fine for fabric version 2.2, Able to create the container using the `createContainer` API. 
<img width="613" alt="creating container working in 2 2" src="https://user-images.githubusercontent.com/56861637/100719442-a6dc1a00-33e2-11eb-9c3c-fba9de543bab.PNG">
The API's after the creation of the container are failing in the test suite because of wrong OU.
The rest of the API calls will be fixed by the issue #1191
