### ISSUE TITLE
Test the addition of new raft orderer on fabric versions 1.4.4 and 2.2.0 with the latest code from branch feature/fabric220

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1161]
### Description
As a developer I want to test the addition of new raft orderer on fabric versions 1.4.4 and 2.2.0 with the latest code from branch feature/fabric220

(add more description and relevant links)

### Acceptance Criteria
1. Addition of new raft orderer should be tested with fabric verison 1.4.4 and 2.2.0.

**Comment by jwavoetacn** [comment]
Validated on version 1.4.4
Network pre-add:
![image](https://user-images.githubusercontent.com/68590662/101174391-1ac92d00-3644-11eb-80d3-9bc1cb900e2a.png)

Network post-add:

**Comment by jwavoetacn** [comment]
Validated on version 2.2.0
Network pre-add:
![image](https://user-images.githubusercontent.com/68590662/101186302-3556d280-3653-11eb-9cd5-ccd3a2bcc4d6.png)

Network post-add (added orderer69):
