### ISSUE TITLE
Test Fabric version 1.4.4 & 2.2.0 compatibility - add new peer

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1163]
### Description
As a developer I want to test the addition of a new peer in existing organization on fabric versions 1.4.4 and 2.2.0 with the latest code from branch feature/fabric220

(add more description and relevant links)

### Acceptance Criteria
1. Addition of a new peer in existing organization should be tested with fabric verison 1.4.4 and 2.2.0.

**Comment by abevers** [comment]
**Validated on version `2.2.0`**
Network with one peer in carrier peer organization:
![2_2_0_post_remove_org](https://user-images.githubusercontent.com/67095118/101177914-9dec8200-3648-11eb-82c9-5ac139e3aec7.PNG)


Network with two peers in carrier peer organization: 
![image](https://user-images.githubusercontent.com/67095118/101177670-5f56c780-3648-11eb-9a94-d5714af654eb.png)
CLI was disabled for peer so not deployed.

**Comment by abevers** [comment]
**Validation for version `1.4.4`**

Network with one peer in carrier peer organization:
![1_4_4_pre_add_peer](https://user-images.githubusercontent.com/67095118/101183528-eeb3a900-364f-11eb-9bd9-2e67c4a8cfa3.PNG)

Network with two peers in carrier peer organization:
![1_4_4_post_add_peer](https://user-images.githubusercontent.com/67095118/101183735-30dcea80-3650-11eb-9469-0ed3a8789c69.PNG)
