### ISSUE TITLE
Test Fabric version 1.4.4 & 2.2.0 compatibility - remove organization

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#1164]
### Description
As a developer I want to test the removal of organization on fabric versions 1.4.4 and 2.2.0 with the latest code from branch feature/fabric220

(add more description and relevant links)

### Acceptance Criteria
1. Test Removal of an organization should be tested with fabric verison 1.4.4 and 2.2.0.

**Comment by abevers** [comment]
**Validated on version `1.4.4`**
Network pre-removal:
![1_4_4_pre_remove_org](https://user-images.githubusercontent.com/67095118/100896662-263f1b80-34bf-11eb-9f57-edd16ac75914.PNG)

Network post-removal:
![image](https://user-images.githubusercontent.com/67095118/100896527-fe4fb800-34be-11eb-9f2e-3a4f8e0b5ed2.png)

We do not have the `discovery` CLI set up, so this is the only way I could validate it for now.

**Comment by abevers** [comment]
**Validated on version `2.2.0`**

Network pre-removal:
![2_2_0_pre_remove_org](https://user-images.githubusercontent.com/67095118/101155021-de3b0880-3626-11eb-8d7b-e04a00af6326.PNG)

Network post-removal:
![2_2_0_post_remove_org](https://user-images.githubusercontent.com/67095118/101155114-f874e680-3626-11eb-9527-6c41df37d340.PNG)
