### ISSUE TITLE
Feature to add a new organization to the consortium

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-labs/blockchain-automation-framework#1168]
**Is your feature request related to a problem? Please describe.**
Ability to
1. Add a new organization to the consortium
2. Add a new consortium to an existing organization

**Describe the solution you'd like**
Provide basic functionalities such as
1. Changing the consortium membership.
2. Ability to create the channel with new organizations that were added after the initial setup.

**Describe alternatives you've considered**
One alternative is to create a channel with only existing organization and then add additional organizations to it. ** Not tested. Also, this lacks a consortium update operation.

**Additional context**
Blockchain Automation Framework creates the consortium in the Hyperledger Fabric with the list of organizations part of the initial network configuration file (Refer to the `network.yaml` file under the sample). This currently blocks an organization from creating a new channel if it's not part of the initial network setup. Also, the existing organization cannot add a new channel with those other organizations which are not part of the consortium.

**Comment by suvajit-sarkar** [comment]
Hi @arsulegai are you currently working at this issue ?

**Comment by arsulegai** [comment]
No, I am still working on other priority items.

**Comment by sownak** [comment]
Part 1 is complete in #1297

**Comment by suvajit-sarkar** [comment]
Confirm if part 1 is complete by checking if org an create a new channel.

**Comment by alvaropicazo** [comment]
Just checked this.

Deployed a network with only one orderer organization and a peer organization (calv, which is the creator). Then, I run the add-organization playbook to create a new organization as a joiner (malv) and expecting to be part of the consortium named "SupplyChainConsortium". As a result, decoding the block into a json file, I checked that both orgs were part of the consortium.

![image](https://user-images.githubusercontent.com/76157062/114564247-70f05180-9c70-11eb-9cb5-e24135dce462.png)

**Comment by arsulegai** [comment]
Thanks @alvaropicazo :)
