### ISSUE TITLE
BAF Script Based Setup for Ubuntu issue

### ISSUE THREAD

**Issue by MASDXI** [hyperledger-labs/blockchain-automation-framework#1170]
Vault version and after unzip script trying to install vault btw vault script response vault install unsuccessful
![Screenshot from 2020-11-11 11-13-03](https://user-images.githubusercontent.com/31649128/98764785-19bf2a00-240f-11eb-8b73-d49e17ad895e.png)

**Comment by sownak** [comment]
The script is only for Mac and Windows (separate scripts). Most likely you have a PATH issue, but the script is not for Ubuntu.
