### ISSUE TITLE
Install new chaincode on existing network does not work unless we mention unique version number(one which was not used for any chaincode deployed before)

### ISSUE THREAD

**Issue by Oreo-Tech** [hyperledger-labs/blockchain-automation-framework#1174]
**Describe the bug**
There seems to be an issue with file names created for install chaincode HelmRelease under release folder for orgs
Example:

  Path: blockchain-automation-framework/platforms/hyperledger-fabric/releases/dev/org/org

  File name: chaincode-install-org-peer0-1.yaml 

The HelmRelease files are created with name in the format  as
"chaincode-install-{{ name }}{{ peer.name }}{{ peer.chaincode.version | replace('.','-')}}"
 
This naming format only includes the chaincode version and peer name but skips out the "chaincode name"
due to this if we already have a chaincode deployed with version 'x' there would be already HelmRelease file for it  (eg: chaincode-install-org-peer0-1.yaml for previously deployed chaincode with version one) when we try to deploy a new chaincode with initial version as 1
the file to be created for the new chaincode fails as there already exist a HelmRelease chaincode deployment file from our earlier deployments of any pervious chaincode with the same version and  the 
"Check if the value file is already present" task in platforms/hyperledger-fabric/configuration/roles/helm_component/tasks/main.yaml file completely skips the part of creating new HelmRelease file for our new chaincode installation with version number same for any perviously installed chaincode
**To Reproduce**
1. Set a already existing fabric network with a chaincode deployed on it with version x (name: samplecc v:1)
2. Now try deploying new chaincode with other different chaincode name but same chaincode version 'x' (name: newsamplecc v:1)
3. Now new Helm relase file won't be created for new chaincode installation (chaincode-install-org-peer0-1.yaml as there is no chaincode name mentioned and HelmRelease file already exists from our earlier deployment)
4. The attempt to install a new chaincode fails with no change on the existing setup

**Expected behavior**
chaincode install should be able to identify different chaincodes based on their name and version and should install the new chaincode succesfully in case its a first time deployment of the chaincode.

**Screenshots**

**Environment (please complete the following information):**
 - Azure Kubernetes
 - Network: 2.0.0
 

**Additional context**

**Comment by suvajit-sarkar** [comment]
This needs to be tested on v2.2 and v1.4.4
