### ISSUE TITLE
Improve validation function for Vault responses

### ISSUE THREAD

**Issue by abevers** [hyperledger-labs/blockchain-automation-framework#1179]
**Issue Description**
Most of the init-containers have a function to validate Vault responses. While this validation function checks for any errors, it does not check for empty or no responses. The init-containers will try to connect to the Vault, but return an empty response. In spite of this, the deployment will continue and causes the pods to have empty certificates, impacting the complete working of the network. See an example of the validation function below.

https://github.com/hyperledger-labs/blockchain-automation-framework/blob/28e4c5b94cb12bf356d8b3b021df6eec347788b4/platforms/hyperledger-fabric/charts/anchorpeer/templates/anchorpeer.yaml#L62-L67

**To Reproduce**
1. Deploy a Hyperledger Fabric network
2. Make sure that the Vault URL is valid, but the Vault is not reachable/is sealed
3. Check the logs of the init-containers of the `ca`, `peer` and `fabric-cli` pod 
4. See logs of the init containers as below

![vault_container_init](https://user-images.githubusercontent.com/67095118/99385742-b3844c80-28d1-11eb-82d4-35ec1bcd1fe0.png)

**Expected behavior**
The validation function of any container that comes in contact with the Vault, should also check for emtpy/no responses. When the Vault is not reachable or returns empty responses, this should be signaled and the deployment should be stopped/retried until the Vault is working correctly.

**Screenshots**
See screenshot above.

**Environment (please complete the following information):**
BAF dev machine

**Additional context**
This might have to be implemented in other platforms as well, not only in Hyperledger Fabric.

**Comment by jagpreetsinghsasan** [comment]
I dont think the network shall validate if the vault is reachable and unsealed after it is setup.
Because the way pods are communicating to the vault, is via vault-kubernetes role (using custom vault token for a given path).

Also, the vault (according to architecture) is recommended to be not a part of the kubernetes cluster, so it wont go down with the cluster. Also if it goes down because of some reason, the pods don't have the privileges to unseal the vault.

**Comment by jwavoetacn** [comment]
Based on the error given in the screenshot, we can do something like:

validateVaultResponse () {
...
if echo ${2} | grep 'could not resolve'; then
 echo "ERROR: unable to retrieve ${1}: ${2}"
 exit 1
fi
}
