### ISSUE TITLE
Supplychain example roles reference a file which was removed in v5

### ISSUE THREAD

**Issue by Singh-Jas** [hyperledger-labs/blockchain-automation-framework#1181]
**Describe the bug**
The roles for creating the sample webserver and for expressapi both reference a role called check/node_component which has since been removed. 

**To Reproduce**
1. Go to the following roles:
       - examples/supplychain-app/configuration/roles/create/corda/expressapi/tasks/main.yaml
       - examples/supplychain-app/configuration/roles/create/corda/webserver/tasks/main.yaml
2. Verify the path defined on line 4 exists
3. Navigate to /r3-corda/configuration/roles/check/node_component
4. File does not exist

**Expected behavior**
These roles cannot be successfully executed as they reference a missing file.

**Comment by jagpreetsinghsasan** [comment]
Yes, this is a valid bug, the check roles have been moved from individual platforms folder to shared folder.
This needs to be updated and also check for other platforms
