### ISSUE TITLE
Making all peers, anchor peers

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#122]
### Description
Currently only peer zero becomes anchor peer when network gets up, need to make all peers anchor peer,

**Comment by suvajit-sarkar** [comment]
Have created a bug #165 for multi peer not working. The bug will be fixed in a separate issue, and is out of the scope for this issue

**Comment by jagpreetsinghsasan** [comment]
Story completed and tested (multipeer with multiorderer)
Here are the screenshots for reference

![beta](https://user-images.githubusercontent.com/56861721/71263356-bbf1a180-2367-11ea-9c39-9cefba156617.PNG)
![delta](https://user-images.githubusercontent.com/56861721/71263358-bbf1a180-2367-11ea-8379-effb7b959684.PNG)
![epsilon](https://user-images.githubusercontent.com/56861721/71263360-bc8a3800-2367-11ea-83c7-aa396ac41f1c.PNG)
![gamma](https://user-images.githubusercontent.com/56861721/71263361-bc8a3800-2367-11ea-992d-26c9886adac1.PNG)
![alpha](https://user-images.githubusercontent.com/56861721/71263362-bd22ce80-2367-11ea-9c15-417fefdcd5a4.PNG)

**Comment by sownak** [comment]
Closed with #167
