### ISSUE TITLE
Enable HTTPS option for BAF Flux

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1220]
### Description
As a developer I want to enable the option to use HTTPS instead of SSH for flux, so that the git repository is used over HTTPS connection

https://docs.fluxcd.io/en/1.20.0/guides/use-git-https/

### Acceptance Criteria
1. Option to use GIT over HTTPS / SSH

**Comment by srinivasansankaran** [comment]
I would like to work on it
