### ISSUE TITLE
Install Ambassador role failing when source IPs are provided

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1231]
**Describe the bug**
The install ambassador role fails when loadBalancerSourceRanges are provided in the network.yaml (configuration file)

**To Reproduce**
1. Provide loadBalancerSourceRanges  in the configuration file under env section
2. Run site.yaml
3. See the error

**Expected behavior**
Playbook completes without error and LB is created with provided source IPs

**Screenshots**
![image](https://user-images.githubusercontent.com/55580532/101786570-16a97d80-3b24-11eb-8575-487f0f57befe.png)

**Environment (please complete the following information):**
 - Branch : Develop

**Comment by jwavoetacn** [comment]
GitHub Actions CI fails which doesn't seem related to my bug fix.
