### ISSUE TITLE
fabric-ca image mapping missing for fabric version 2.2.0

### ISSUE THREAD

**Issue by sidnaik1989** [hyperledger-labs/blockchain-automation-framework#1245]
**Describe the bug**
There is no mapping added for Fabric version 2.2.0 to the fabric-ca image version in files  
platforms/hyperledger-fabric/configuration/roles/create/ca-server/vars/main.yaml  
platforms/hyperledger-fabric/configuration/roles/create/peers/vars/main.yaml  
in master branch

**To Reproduce**
1. Clone latest code from BAF repo
2. Setup network.yaml with fabric version 2.0.0
3. Setup all required pre-requisites and run deployment playbooks
3. Deployment fails while creating vaues.yaml file for ca-server. Error: 'dict object' has no attribute u'2.2.0'

**Expected behavior**
Deployment should succeed

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Version [18.04LTS]

**Comment by suvajit-sarkar** [comment]
Currently HL Fabric v2.2 is under development, you can use the develop branch to try it out, or w8 for our release

**Comment by suvajit-sarkar** [comment]
Closing the issue as the Fabric v2.2 should now be available of master branch
