### ISSUE TITLE
Issue while using different tlsca

### ISSUE THREAD

**Issue by rahultoraskarr** [hyperledger-labs/blockchain-automation-framework#1263]
**Describe the bug**

Value of CORE_PEER_TLS_ROOTCERT_FILE on helm charts for fabric cli, fabric channel and chaincode related kubernetes jobs is pointing to CA instead of TLSCA. This caused connection issue between cli( and other kubernetes jobs) and peer when different CA is used for tls certificates.

**To reproduce**
Create the TLS certs using a  different CA. The fabric cli and the subsequent jobs will fail to finish.

**Expected behaviour**
If we mention the correct CA for TLS, the jobs and CLI pods shall not fail to finish/execute

**Environment**
Release 0.7.0.0 BAF repo master code used

**Comment by alvaropicazo** [comment]
I'll be working on this.
