### ISSUE TITLE
Manually add validator node to the existing validator organization in a BAF HL Besu network 

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1276]
### Description
As a developer I want to manually add a new validator node in existing besu network. 
Steps:
1.Deploy sample Besu network using BAF
2.Refer to the documentation for adding a validator peer using ibft_proposeValidatorVote api method.
3.Perform the manual addition of a new validator node on the baf deployed Besu network
4.Document the next steps for automation

### Acceptance Criteria
1. Successful manual addition of validator node to existing validator organization 
2. Documentation is clear to proceed for automation

**Comment by ragalz** [comment]
Next steps: 

1. Add a new validator within existing organization.
      - Use different network.yaml referencing the existing org & containing new validator data.
      - New network.yaml should also contain the URLs of the existing validators.
      - Create all necessary node artifacts through an ansible playbook
      - Use ansible to make RPC calls to validator nodes in order to join the new validator. 

2. Add new organization with validator.
      - Use different network.yaml containing the data needed (Org & validator data).
      - New network.yaml should also contain the URLs of the existing validators.
      - Create all necessary node and organization artifacts through an ansible playbook
      - Use ansible to make RPC calls to validator nodes in order to join the new validator.
