### ISSUE TITLE
Value file in Indy charts do not have correct help documentation

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#128]
**Describe the bug**
The values.yaml file in each of the Indy charts do not have correct help documentation. The values file should contain description of each key and  a sample value.

**To Reproduce**
1. Go to 'platforms\hyperledger-indy\charts\indy-domain-genesis'
2. Open 'values.yaml'
3. The keys like 'namespace' do not have a correct comment.
4. This applies to all values.yaml file in all the charts under platforms\hyperledger-indy\charts folder.

**Expected behavior**
A clear and concise comment and a sample value should be provided for each key in values.yaml

**Additional context**
Also the README.md in  platforms\hyperledger-indy\charts should be updated to summarize the charts and their functions. The README.md in each chart directory is not needed.

**Comment by juraj-durech** [comment]
Closed by #232
