### ISSUE TITLE
Indy Ansible roles need correct readme

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#129]
**Describe the bug**
All the Ansible roles in folder platforms\hyperledger-indy\configuration\roles does not have any readme document.

**To Reproduce**
1. Go to 'platforms\hyperledger-indy\configuration\roles'
2. Go to 'check/crypto' folder
3. There is no README.md
4. This applies to all the roles under platforms\hyperledger-indy\configuration\roles

**Expected behavior**
A clear readme should be added to each role specifying what the role does, what input and output is needed.

**Additional context**
The readme.md in folder platforms\hyperledger-indy\configuration\roles can be removed if all information is provided in the corresponding roles.

**Comment by juraj-durech** [comment]
Closed by #235
