### ISSUE TITLE
Namespace for the flux

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-labs/blockchain-automation-framework#1292]
**Is your feature request related to a problem? Please describe.**
The flux gets installed in the default namespace. However, in the production setup it would be better to have the installation happening on a separate namespace. The custom namespace can enable administrators to apply restrictions and perform other integrations without affecting the network.

**Describe the solution you'd like**
Install flux in its own namespace.

**Describe alternatives you've considered**
Install flux outside the BAF.

**Additional context**
Having flux installed in its own namespace will help.

**Comment by pppazos** [comment]
I can work this issue.

**Comment by arsulegai** [comment]
> I can work this issue.

Thanks, that would help
