### ISSUE TITLE
Organization that is not part of the channel is not added to orderer genesis

### ISSUE THREAD

**Issue by rahultoraskarr** [hyperledger-labs/blockchain-automation-framework#1294]
**Describe the bug**
I am trying to create Hyperledger Fabric network with 3 orgs, say A,B and C. I need two channels on the network, one with orgs (A, B) and other with orgs (A, C).

Due to limitation in BAF, I can only specify one channel when creating a network. When creating network with all 3 orgs and only A and B in channel, org C doesn't get added to consortium or genesis block. Due to which when running playbook 'add-new-channel.yaml' to create second channel (A, C) I get below error

Error: got unexpected status: BAD_REQUEST -- Attempted to include member C which is not in the consortium

**To Reproduce**
Create a Fabric network with 3 orgs and add only two orgs to the channel

**Expected behavior**
All orgs in the network should be part of consortium 

**Environment (please complete the following information):**
 - Version : 2.2.0

**Comment by alvaropicazo** [comment]
![image](https://user-images.githubusercontent.com/76157062/107761043-03d14600-6d2b-11eb-9960-04c91b6ee4f7.png)

This is how the system channel looks when there are three Orgs in the network and two Orgs in the channel.

**Comment by alvaropicazo** [comment]
A new issue has been created related to adding a new channel to the existing network, as also was part of the error that was being faced in this issue. To see more details regarding the issue and have a tracking, can be done here: #1304
