### ISSUE TITLE
Run the ansible playbook  for fabric in gke return error form storage class.

### ISSUE THREAD

**Issue by brando14** [hyperledger-labs/blockchain-automation-framework#1295]
**Describe the bug**
Hello, I try to deploy the principal example from BAF in fabric version,  when I deploy the playbook I get this error regarding the storage class:

TASK [create/storageclass : Create Storage Class value file for orderers] *******************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'gcp-orderer'\n\nThe error appears to be in '/home/brando/blockchain-automation-framework/platforms/hyperledger-fabric/configuration/roles/create/storageclass/tasks/main.yaml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# This task creates the value file for creating the storage class for Orderer\n- name: Create Storage Class value file for orderers\n  ^ here\n"}

The cluster is created in gcp, that is, it is a gke cluster.

Please could you give me some idea why this error?

**To Reproduce**
1. Fork the baf repository and clone.
2. Install prerequisites of baf
2. Create file name build and  create fabric-network.yaml following the documentation and specifying that the cluster provider is gcp.
3. Run the ansible principal command 

**Expected behavior**
the fabric network running in gke cluster.

**Environment (please complete the following information):**
 -  ubuntu 20.04 LTS
 -  fabric 2.2.0

**Comment by jagpreetsinghsasan** [comment]
Currently we have storage class templates for EKS, AKS and minikube. For GKE, we need to have the storage classes in place, so that the BAF deployment can work for the Google Managed Kubernetes service.

Here's an operational guide, to implement the same
https://blockchain-automation-framework.readthedocs.io/en/latest/operations/adding_new_storageclass.html

**Comment by brando14** [comment]
@jagpreetsinghsasan  thanks my friend for the help

**Comment by Roshan13046** [comment]
I would like to fix this issue by adding a gcp-storageclass.tpl template file inside the hyperledger-besu platform directory having path `blockchain-automation-framework/platforms/hyperledger-besu/configuration/roles/create/k8_component/templates` along with any entry in `project/blockchain-automation-framework/platforms/hyperledger-besu/configuration/roles/create/k8_component/vars/main.yaml`
