### ISSUE TITLE
Approve chaincode check is incorrect

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1296]
**Describe the bug**
The ansible task to create value files for approve chaincode has a check which first verifies if the chaincode is already approved or not. That check is incorrect and always passes.
 [This](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/4e46b975c0d90a93bf3081e407b807c9e26dd142/platforms/hyperledger-fabric/configuration/roles/create/chaincode/approve/tasks/valuefile.yaml#L25) is what the label selector in the ansible task is written, and is different from the actual label selector in the chart as mentioned [here](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/4e46b975c0d90a93bf3081e407b807c9e26dd142/platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml#L7)
 
 I am attaching the screenshots for reference, in case, the code gets changed and then the lines wont matched the above referenced lines
 
 The chart
![image](https://user-images.githubusercontent.com/56861721/107465736-eb292a80-6b88-11eb-85c8-23d32a230d9d.png)

The ansible code
![image](https://user-images.githubusercontent.com/56861721/107467601-6213f280-6b8c-11eb-80b6-622bb755c863.png)

**Comment by brando14** [comment]
@jagpreetsinghsasan  
could this affect when approving the chaindoce ?, since I have problems when the job that approves the chaincode is lifted, since it cannot find some files where some credentials are.

**Comment by jagpreetsinghsasan** [comment]
Issue #1320 has already fixed this.
