### ISSUE TITLE
Indy sample configuration file does not have proper comments.

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#130]
**Describe the bug**
The Indy sample configuration file (platforms\hyperledger-indy\configuration\samples\network-indyv3.yaml) does not have any comment so it is difficult for users to understand what the keys are for and what values are supported.

**To Reproduce**
1. Go to 'platforms\hyperledger-indy\configuration\samples\network-indyv3.yaml'
2. The keys and values do not have any documentation.

**Expected behavior**
The sample network.yaml file should contain all documentation and comments necessary to understand each key/value in the yaml file.

**Comment by juraj-durech** [comment]
Closed by #243
