### ISSUE TITLE
BAF with fabric can not approve chaincode: Error: failed to retrieve endorser client for approveformyorg: failed to load config for PeerClient: unable to load peer.tls.rootcert.file: open /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/tlscacerts/tlsca.crt: no such file or directory 

### ISSUE THREAD

**Issue by brando14** [hyperledger-labs/blockchain-automation-framework#1301]
**Describe the bug**
when i run the playbook and reaches the part of approving the chaincode, the following error will occur:

Error: failed to retrieve endorser client for approveformyorg: failed to load config for PeerClient: unable to load peer.tls.rootcert.file: open /opt/gopath/src/github.com/hyperledger/fabric/crypto/admin/msp/tlscacerts/tlsca.crt: no such file or directory 

from what i saw it can't find the directory where the credentials are.
and the job can not work.

any idea why these occur?

**Expected behavior**
Chaincode approve 

**Environment (please complete the following information):**
 - Fabric 2.2.0
 - Gke

**Comment by maximusGit** [comment]
I have the same issue.

**Comment by jagpreetsinghsasan** [comment]
Yes, this bug is valid (temporary)
It will be fixed with the PR #1302
(It was just that the tlscacerts folders weren't created, so the certs weren't getting pasted to those paths, this PR will fix the same)

**Comment by suvajit-sarkar** [comment]
The PR #1302 is merged let us know if you still facing the same issue

**Comment by brando14** [comment]
@suvajit-sarkar ok , Thank you very much for the information, I will try this

**Comment by brando14** [comment]
@jagpreetsinghsasan 

works fine, but now i have this error when the approve chaincode is deployed.

Error: timed out waiting for txid on all peers

any idea that means this?

**Comment by brando14** [comment]
@jagpreetsinghsasan @suvajit-sarkar 

now i have this issue, when the job of approve chaincode going to run.

Error: timed out waiting for txid on all peers

**Comment by suvajit-sarkar** [comment]
@alvaropicazo can you kindly have a look

**Comment by alvaropicazo** [comment]
Sure. So @brando14 I am able to deploy the network successfully, so maybe could you explain me how are you reaching that error? I guess you are not being able to deploy it successfully, so what kind scenario are you trying to have? Peers, orgs.. just to try what you are trying and have a look on what is happening

**Comment by brando14** [comment]
@alvaropicazo 

sure and sorry for the delay, well I'm trying to display the main example, that is the site.yaml with the network.yaml.

I do this in a gke cluster, so I had to add the template for the gcp storage class.

Well edit the network.yaml according to the documentation, in this case I use only one orderer and 2 peers, I have neither the external dns nor the frontend option enabled and I am using the supplychain example chaincode.

when it comes to the part of lifting the job to approve the chaincode and after fixing the credentials, it throws me the following error.

![image](https://user-images.githubusercontent.com/46904374/109150040-b4cddc80-773e-11eb-9fdf-3b62210b80b1.png)

What could it be?

**Comment by alvaropicazo** [comment]
thanks @brando14 so trying to deploy scenario, I am getting it right.
![image](https://user-images.githubusercontent.com/76157062/109303823-9dc0e480-783b-11eb-8981-9ce4a1b48bff.png)
These logs are from the approve chaincode. I can see that your logs are from 12 of February, and on that date the issues were not fixed yet..

**Comment by brando14** [comment]
ok @alvaropicazo  thanks for the help i going to upgrade the repo and test.

and a question

is there a way to not use a dns configuration to get this network up?

**Comment by suvajit-sarkar** [comment]
@brando14 we will be closing this bug, please feel free to get in touch with us on the [rocketchat ](https://chat.hyperledger.org/channel/blockchain-automation-framework)incase you are facing some issue
