### ISSUE TITLE
CC Deployment is getting failed in a peer added in an existing hyperledger fabric network(v2.2.0) using baf

### ISSUE THREAD

**Issue by SoundaryaA3098** [hyperledger-labs/blockchain-automation-framework#1307]
**Describe the bug**
 I tried to add a new peer in the existing org in an existing network (Fabric v2.2.0) using baf. It was successful and the new peer has also joined the channel. But the chaincode deployment is throwing error in new peer. I am able to package the chaincode and install the chaincode, but the "approvemyorg" is throwing error like below,
**Error: timed out waiting for txid on all peers**
So, I did the approvemyorg step from the peer which was there from the initial network deployment. There the approval was successful. Then I used "peer lifecycle chaincode checkcommitreadiness" command to check the orgs those who have got approved in the new peer, it is showing the below result,
{
"approvals": {
"abcMSP": false,
"defMSP": false
}
}
But if I try the same command in an old peer, it says the right result,
{
"approvals": {
"abcMSP": true,
"defMSP": true
}
}
Also, the invoke or query in the new peer is throwing,
Error: endorsement failure during invoke. response: status:500 message:"make sure the chaincode fabcarv3 has been successfully defined on channel intainchannel and try again: chaincode fabcarv3 not found"
Error: endorsement failure during query. response: status:500 message:"make sure the chaincode fabcarv3 has been successfully defined on channel intainchannel and try again: chaincode fabcarv3 not found".

**To Reproduce**
Deploy an hyperledger fabric network (v2.2.0) using blockchain-automation-framework. Once the network deployment is completed, add a new peer using baf using the steps in the documentation - https://blockchain-automation-framework.readthedocs.io/en/develop/operations/adding_new_peer_fabric.html.  Once the new peer is added to an existing org and joined the channel, deploy the chaincode in the new peer.

**Expected behavior**
Chaincode is successfully deployed and invoke and query are working as expected.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Additional context**

**Comment by brando14** [comment]
i have the same issue.

**Comment by SoundaryaA3098** [comment]
Additional info, the following channel info is from old peer of the org,

**bash-5.0# peer channel getinfo -c mychannel
2021-02-19 09:32:10.533 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Blockchain info: {"height":9,"currentBlockHash":"3JWXNwGt9rhGldFcUyBqjWizsOKRbQBKY3KNvBl6rA8=","previousBlockHash":"oIlDSVnCj4fOkozTjN2BDDLIs16RwooQy59qI1P9Eu4="}**

The below result is from the new peer,

**bash-5.0# peer channel getinfo -c mychannel
2021-02-19 09:40:59.093 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Blockchain info: {"height":1,"currentBlockHash":"3WnnD9/ZMu56urG8Mdzw4/VHvCZOkCssCf+AyyWATGs="}**

This difference is the cause for the CC to not work in the new peer. I guess this info gives some more view on the issue.

**Comment by jagpreetsinghsasan** [comment]
Thanks for the finding @SoundaryaA3098 . This surely helps.
