### ISSUE TITLE
Readme file in Indy configuration directory is empty

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#131]
**Describe the bug**
The README.md file at platforms\hyperledger-indy\configuration\README.md does not have proper content.

**To Reproduce**
1. Go to 'platforms\hyperledger-indy\configuration\README.md'
2. This file should have required information on how to run the playbooks.

**Expected behavior**
The readme file should describe the playbooks and how to execute them.

**Additional context**
Check existing readme files at platforms\r3-corda\configuration\README.md for guidance

**Comment by juraj-durech** [comment]
Closed via #238
