### ISSUE TITLE
Fix and test existing molecule test for Fabric

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1314]
### Description
As a developer, I want to test the existing molecule tests for Fabric platform

The existing molecule tests are located [here](https://github.com/hyperledger-labs/blockchain-automation-framework/tree/master/platforms/hyperledger-fabric/configuration/molecule).

These tests were written long back (2months, 9months ago) and needed to be fixed first before we start creating the new molecule tests.

### Acceptance Criteria
1. All the existing molecule tests for Fabric should run successfully.

**Comment by TonyRowntree99** [comment]
Test @suvajit-sarkar

**Comment by TonyRowntree** [comment]
Commenting with my new account

**Comment by TonyRowntree** [comment]
Test **passed** with some syntax warnings


![fabricMoleculeTest](https://user-images.githubusercontent.com/33454202/110357925-ba2b0100-8033-11eb-8863-e60278b5c3ff.png)

**Comment by TonyRowntree** [comment]
Test now running as should after correcting the syntax errors. One of the tasks is now 
failing (see below) @jagpreetsinghsasan 

![FailedTask](https://user-images.githubusercontent.com/33454202/110610782-785e9f80-8186-11eb-9bab-b2340397479b.png)

**Comment by TonyRowntree** [comment]
All **current** fabric molecule tests running correctly with no failures, will create PR for this.

Crypto - 
![image](https://user-images.githubusercontent.com/33454202/111286605-4643b680-863a-11eb-9248-75fca91d0f60.png)

Pre-Vault -
![image](https://user-images.githubusercontent.com/33454202/111287281-fa454180-863a-11eb-957a-ab2809efdad1.png)

Default -
![image](https://user-images.githubusercontent.com/33454202/111287867-8ce5e080-863b-11eb-89d0-a10a16b03cc6.png)
