### ISSUE TITLE
Vault kv store version 2 support

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-labs/blockchain-automation-framework#1317]
**Is your feature request related to a problem? Please describe.**
Having v2 supported kv storage in Vault allows to keep backup identities. Also, facilitating the cert refresh in leisure instead of force restarting the nodes to refresh the certs.

**Describe the solution you'd like**
Update the kv storage to v2.

**Describe alternatives you've considered**
None

**Additional context**
Enabling v2 for Vault may create complications in BAF.

**Comment by sownak** [comment]
Updates needed to upgrade Vault to kv2 for Fabric

1. Manually enable separate secret path with v2 `vault secrets enable -version=2 -path=secretsv2 kv`
2. Update network.yaml with new path `secretsv2` in `vault.secret_path`
3. Update `platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/templates` policy templates to include data like `path "{{ vault_secret_path }}/data/***" {`
4. Replace all `vault write` which creates keys with `vault kv put`
5. Update roles `setup/get_ambassador_crypto` and `setup/get_crypto` as the yaml output format has changed.
6. Replace all `vault delete` which deletes keys with `vault kv delete`
7. Command `vault kv get -format=yaml` will not fail if secrets do not exists, update ansible when conditions accordingly to check if the secret was deleted.
