### ISSUE TITLE
Indy node image does not have correct readme

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#132]
**Describe the bug**
The indy-node docker image does not have correct readme

**To Reproduce**
1. Go to 'platforms\hyperledger-indy\images\indy-node'
2. Open 'README.md'
3. The readme does not have correct information

**Expected behavior**
The readme should contains instructions to build the docker image and when the image is needed.

**Additional context**
The readme.md at platforms\hyperledger-indy\images should also be updated with description of the various images and their necessity.

**Comment by juraj-durech** [comment]
Closed by #246
