### ISSUE TITLE
Chaincode Intall and approve failed

### ISSUE THREAD

**Issue by brando14** [hyperledger-labs/blockchain-automation-framework#1326]
**Describe the bug**
hello i forked this repository with the updates.

1) first i install and configured the prerequisites following the oficcial documentation

install:
https://blockchain-automation-framework.readthedocs.io/en/latest/prerequisites.html

configure:

https://blockchain-automation-framework.readthedocs.io/en/latest/operations/configure_prerequisites.html

2)  I edited the  [network.yaml](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/master/platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml) of example for use one orderer and two organizations and put it in a folder called build.

the edition looks like this images:

a)  I use the fabric plataform without the frontend and external dns.

![image](https://user-images.githubusercontent.com/46904374/109971809-03462280-7ccd-11eb-8f6f-9f6039000d3c.png)

b) I only use two organizations with one orderer.
![image](https://user-images.githubusercontent.com/46904374/110019240-9f3c5200-7cfe-11eb-9241-960bb109b521.png)

c) this tree elements have the same external uri suffix:

![image](https://user-images.githubusercontent.com/46904374/109972015-3ab4cf00-7ccd-11eb-9b31-e52810cc38c8.png)

d)  i added my own chaincode:

![image](https://user-images.githubusercontent.com/46904374/110012103-89c32a00-7cf6-11eb-98a0-2b74fb8e7966.png)

3) it is to highlight that I am using  a cluster in gcp for run the network and i already have done the test on two types of container runtime ( one is the docker and the other the containerd).

4) when i run the ansible command:

`ansible-playbook platforms/shared/configuration/site.yaml --inventory-file=platforms/shared/inventory/  -e "@./build/network.yaml" -e 'ansible_python_interpreter=/usr/bin/python3' `

and come to the part in the chaincode going to be installed I get the following errors:
 
a) If it is the example chaincode, it can be installed but when it seeks to be approved it gives me the following error:

Error: timed out waiting for txid on all peers

I had already commented on this error in the previous issue but I updated the repository and it still does not happen to me.

b) If the chaincode is another (my case), it won't install it and the results show me that the chaincode no exist.

I have checked the installation template to see some hint why it happens, but I am still new to ansible and kubernetes.

I found the following:

![image](https://user-images.githubusercontent.com/46904374/110015724-947fbe00-7cfa-11eb-876c-2e6d29b18771.png)

From what I understand the chaincode is cloned using my github credentials and it is stored in the tmp folder of the container then it is copied to the chaincode folder. Then a variable is exported which refers to the directory where the chaincode will be packaged. However that variable refers to the chaincode's main.go being found inside a folder named after the chaincode's name. 

I edited this since my chaincode folder is configured differently, so now it appears to me that it is. However it gives me the following error:

Error: error getting chaincode bytes: failed to calculate dependencies: incomplete package: github.com/hyperledger/fabric-contract-api-go/contractapi

from what I saw is due to the lack of some dependencies, so what should I do to be able to download these dependencies?.

**Environment (please complete the following information):**
 -  GKE Cluster
 -  Docker and Containerd runtimes

**Comment by brando14** [comment]
another question with what type of containers run in k8s with docker or containerd?

**Comment by jagpreetsinghsasan** [comment]
Same as issue #1307

**Comment by sownak** [comment]
Closed because it is the same issue #1307
