### ISSUE TITLE
Fix and test the exisitng molecule tests written for Corda

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1327]
### Description
As a developer, I want to test the existing molecule tests for R3-Corda platform

The existing molecule tests are located [here](https://github.com/hyperledger-labs/blockchain-automation-framework/tree/master/platforms/r3-corda/configuration/molecule).

These tests were written long back (2months ago) and needed to be fixed first before we start creating the new molecule tests.

### Acceptance Criteria
1. All the existing molecule tests for R3-Corda should run successfully.

**Comment by angelaalagbe** [comment]
I'll take this task

**Comment by sownak** [comment]
@all-contributors please add @angelaalagbe as our new contributor

**Comment by sownak** [comment]
@all-contributors please add @jagpreetsinghsasan  for mentoring

**Comment by angelaalagbe** [comment]
I've completed this task
