### ISSUE TITLE
When is the Hyperledger Besu project ready?

### ISSUE THREAD

**Issue by mohjam2004** [hyperledger-labs/blockchain-automation-framework#1336]
Hi,
I want to deploy Hyperledger Besu on kubernetes cluster. When is the first release of this project ready?
thanx in advance.

**Comment by sownak** [comment]
@mohjam2004 HL besu is already available since release 0.6.0.0 https://github.com/hyperledger-labs/blockchain-automation-framework/releases/tag/v0.6.0.0

In future, for questions, please use rocketchat https://chat.hyperledger.org/channel/blockchain-automation-framework
