### ISSUE TITLE
Indy prerequisites on readthedocs

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#134]
### Description
As a user I want to understand about the prerequisites for Hyperledger Indy so that I can configure all dependencies before deploying the Indy platform.

Update the docs docs\source\prerequisites.md and docs\source\operations\configure_prerequisites.md to provide information for any new prerequsistes needed for Hyperledger Indy

### Acceptance Criteria
1. Updated prerequisites.md
2. Updated configure_prerequisites.md

**Comment by juraj-durech** [comment]
Closed via #272
