### ISSUE TITLE
Spike: Vault KV2 support

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1346]
### Description
As a developer, I want to have kv2 secret engine support for Hashicorp vault.
https://www.vaultproject.io/docs/secrets/kv/kv-v2

### Acceptance Criteria
1. Update description and acceptance criteria for #1317
2. The description should be sufficient enough to start 1317 by another develop

**Comment by sownak** [comment]
Updates needed to upgrade Vault to kv2 for Fabric. Similar changes will be needed for all platforms

1. Manually enable separate secret path with v2 `vault secrets enable -version=2 -path=secretsv2 kv`
2. Update network.yaml with new path `secretsv2` in `vault.secret_path`
3. Update `platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/templates` policy templates to include data like `path "{{ vault_secret_path }}/data/***" {`
4. Replace all `vault write` which creates keys with `vault kv put`
5. Update roles `setup/get_ambassador_crypto` and `setup/get_crypto` as the yaml output format has changed.
6. Replace all `vault delete` which deletes keys with `vault kv delete`
7. Command `vault kv get -format=yaml` will not fail if secrets do not exists, update ansible when conditions accordingly to check if the secret was deleted.
