### ISSUE TITLE
Use BAF in a non-managed Kubernetes Cluster (One ordinary Kubernetes cluster on Non-Cloud Providers)

### ISSUE THREAD

**Issue by mohjam2004** [hyperledger-labs/blockchain-automation-framework#1361]
I have deployed a kubernetes cluster with 3 nodes. My nodes are VMs created in physical server (I have no cloud provider for my cluster nodes).
I have another node in which I have installed haproxy to expose my cluster services to outside world and I have defined a wildcard dns recored to point to haproxy public IP address to define different url for each service published outside.
My cluster dns service is core-dns and this service do my name resolution in cluster.
All my nodes (VMs) have a static public and private IP address.
I have installed ansible in haproxy node. the haproxy node has access to cluster through kubectl cli too.
I have deployed Vault to my kubernets cluster through helm chart and it works.
I have done all pre-requisites but I have some question on network.yml file.
what consideration I must take to edit this file correctly:
how to complete this parts:

![image](https://user-images.githubusercontent.com/59224403/112745435-95380700-8fbd-11eb-88c4-c1fe0373b7d6.png)

![image](https://user-images.githubusercontent.com/59224403/112745436-9b2de800-8fbd-11eb-9e3a-1c6de201f722.png)

![image](https://user-images.githubusercontent.com/59224403/112745440-a254f600-8fbd-11eb-9b8f-7dec147cc330.png)

![image](https://user-images.githubusercontent.com/59224403/112745840-90288700-8fc0-11eb-9a75-4d745addf999.png)

![image](https://user-images.githubusercontent.com/59224403/112745883-ce25ab00-8fc0-11eb-9b48-b7db1f505f79.png)

**Comment by mohjam2004** [comment]
This platform do all installation from the beginning, for example install kubectl, helm, ... .
My cluster is  ready and up and I can manage my cluster with kubectl cli.
I have installed vault into my cluster and I have its url and I can log in to with root token.
Now how can I use this platform?
I run the script according to :
![image](https://user-images.githubusercontent.com/59224403/112750706-6b8fd780-8fdf-11eb-8fc0-992ec38f6d1d.png)
and I got this error:
![image](https://user-images.githubusercontent.com/59224403/112750725-7d717a80-8fdf-11eb-9c06-cb347bb734a2.png)

**Comment by mohjam2004** [comment]
I'm sure many people or companies have my condition. They have a ready kubernetes cluster and have a node by which manage the cluster (kubectl and helm) and a node by which (haproxy installed) they expose kubernetes services to outside world, this node can be the same as the node by which they manage the cluster(kubectl and helm).
Is there any doc for this condition to deploy blockchain networks through this platform (BAF)?

**Comment by sownak** [comment]
@mohjam2004 For BAF to work with your own Kubernetes cluster, you have to make the appropriate changes like add support for a new cloud_provider. You can check the code as as to where all cloud_provider value is used and update the code as per your own cloud_provider value.

**Comment by sownak** [comment]
Closing issue as per discussion above.
