### ISSUE TITLE
Improve validation function for Vault responses for besu and quorum helm charts

### ISSUE THREAD

**Issue by deepakkumardbd** [hyperledger-labs/blockchain-automation-framework#1364]
### Description
The validation function of any container that comes in contact with the Vault, should also check for empty/no responses. When the Vault is not reachable or returns empty responses, this should be signaled and the deployment should be stopped/retried until the Vault is working correctly

### Acceptance Criteria

1. Validation function is able to catch all errors
2. The container should retry for given threshold incase of error

**Comment by jagpreetsinghsasan** [comment]
Refer to this PR (and the issue attached to the PR) on how to progress on the same.
https://github.com/hyperledger-labs/blockchain-automation-framework/pull/1333

**Comment by mgCepeda** [comment]
I'm going to work on this issue
