### ISSUE TITLE
[Fabric] Add a new organization to the ordering service cluster

### ISSUE THREAD

**Issue by arsulegai** [hyperledger-labs/blockchain-automation-framework#1374]
**Is your feature request related to a problem? Please describe.**
In use cases, organizations prefer to divide and maintain ordering service cluster nodes. The feature here is to enable BAF to setup ordering service cluster across organizations but still work in unison.

**Describe the solution you'd like**
Ability to add a new organization to the existing ordering service cluster.

**Describe alternatives you've considered**
None, this can be done manually outside the BAF.

**Additional context**
N/A

**Comment by suvajit-sarkar** [comment]
Hi @arsulegai thanks for creating the issue, but we already have an issue for the same and we are currently working on it. 
Please find the issue here : #614
