### ISSUE TITLE
Joinchannel and Anchor Peer Updation tasks resulted in failure for a configuration with multiple channels in hyperledger fabric network using BAF

### ISSUE THREAD

**Issue by SoundaryaA3098** [hyperledger-labs/blockchain-automation-framework#1392]
**Describe the bug**

Using the latest release v0.8.0.0 in BAF, I have deployed a hyperledger fabric network v2.2.0. The network.yaml is configured in such a way that the network has 2 channels. The channel creation was successful for both the configured channels. But the joinchannel job and anchor peer updation job were resulted in failure. That means, the pods even were not created for joinchannel and anchor peer updation.

**To Reproduce**

1. Choose v0.8.0.0 release of BAF and v2.2.0 for hyperledger fabric.
2. Configure the network.yaml with multiple channels.
3. Start the deployment and wait for channel creation (for all the configured channels) to get completed.
4. After create channel job is done, will be able to see the retries for joinchannel get exceeded 
and the deployment will be left incomplete with joinchannel and anchor peer updation for all the orgs.

**Expected behavior**
The joinchannel job and anchor peer updation tasks should have got triggered properly once the createchannel job is done.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 18.04]

**Additional context**

. Since the pods itself not created for joinchannel and anchor peer updation, unable to capture the logs of both the jobs. But, attaching the logs of flux-dev pod and flux-dev-helm-operator pods,

**flux-dev logs:**

helmrelease.helm.fluxcd.io/joinchannel-peer0-join-mychannel-org2-peer0 created\nhelmrelease.helm.fluxcd.io/joinchannel-peer0-join-mychannel-org3-peer0 created\nhelmrelease.helm.fluxcd.io/joinchannel-peer0-join-mychannel-org1-peer0 created\nhelmrelease.helm.fluxcd.io/org2-net-ca unchanged\nhelmrelease.helm.fluxcd.io/org2-net-ca-tools unchanged\nhelmrelease.helm.fluxcd.io/org2-peer0 unchanged\nhelmrelease.helm.fluxcd.io/org3-net-ca unchanged\nhelmrelease.helm.fluxcd.io/org3-net-ca-tools unchanged\nhelmrelease.helm.fluxcd.io/org3-peer0 unchanged\nhelmrelease.helm.fluxcd.io/org1-net-ca unchanged\nhelmrelease.helm.fluxcd.io/org1-net-ca-tools unchanged\nhelmrelease.helm.fluxcd.io/org1-peer0 unchanged"
ts=2021-04-09T06:32:24.680903785Z caller=daemon.go:701 component=daemon event="Sync: d5fcc72..96714b4, org2-net:helmrelease/joinchannel-peer0-join-mychannel-org2-peer0, org3-net:helmrelease/joinchannel-peer0-join-mychannel-org3-peer0, org1-net:helmrelease/joinchannel-peer0-join-mychannel-org1-peer0"

**flux-dev-helm-operator:**

component=release release=joinchannel-peer0-join-mychannel-org3-peer0 targetNamespace=org3-net resource=org3-net:helmrelease/joinchannel-peer0-join-mychannel-org3-peer0 helmVersion=v3 error="failed to determine sync action for release: failed to retrieve Helm release: releaseContent: Release name is invalid: joinchannel-peer0-join-mychannel-org3-peer0"

Also, attaching the network.yaml file I have used.

[network.txt](https://github.com/hyperledger-labs/blockchain-automation-framework/files/6284785/network.txt)

**Comment by sownak** [comment]
As mentioned in the chat, please share the status of the helmrelease CRD `kubectl get helmrelease -A` and then `kubectl describe helmrelease -n <namespace> <helmreleasename>`

**Comment by SoundaryaA3098** [comment]
Describe of helmrelease has the following event,

Warning FailedReleaseSync 3m29s (x192 over 9h) helm-operator synchronization of release 'joinchannel-peer0-join-mychannel-org1-peer0' in namespace 'org1-net' failed: failed to determine sync action for release: failed to retrieve Helm release: releaseContent: Release name is invalid: joinchannel-peer0-join-mychannel-org1-peer0

**Comment by sownak** [comment]
That seems like you had previous installations. Try deleting the helmrelease

**Comment by SoundaryaA3098** [comment]
I tried deleting the helmrelease (joinchannel-peer0-join-mychannel-org1-peer0), it got deleted. In the flux pods, I see the below logs:
ts=2021-04-12T05:17:03.702614368Z caller=release.go:422 component=release release=joinchannel-peer0-join-mychannel-org1-peer0 targetNamespace=org1-net resource=org1-net:helmrelease/joinchannel-peer0-join-mychannel-org1-peer0 helmVersion=v3 info="running uninstall" phase=uninstall
ts=2021-04-12T05:17:03.70636884Z caller=release.go:424 component=release release=joinchannel-peer0-join-mychannel-org1-peer0 targetNamespace=org1-net resource=org1-net:helmrelease/joinchannel-peer0-join-mychannel-org1-peer0 helmVersion=v3 warning="uninstall failed: uninstall: Release name is invalid: joinchannel-peer0-join-mychannel-org1-peer0" phase=uninstall

**Comment by sownak** [comment]
@SoundaryaA3098 the releases should come up automatically if you are still using flux.

**Comment by SoundaryaA3098** [comment]
> @SoundaryaA3098 the releases should come up automatically if you are still using flux.

The flux is still running in the cluster, also in the flux logs, I can see:
caller=release.go:109 component=release release=joinchannel-peer0-join-mychannel-org2-peer0 targetNamespace=org2-net resource=org2-net:helmrelease/joinchannel-peer0-join-mychannel-org2-peer0 helmVersion=v3 error="failed to determine sync action for release: failed to retrieve Helm release: releaseContent: Release name is invalid: joinchannel-peer0-join-mychannel-org2-peer0"

I guess again there is an error while trying to sync.

**Comment by alvaropicazo** [comment]
Hi @SoundaryaA3098 , we tested multiple channel creation on #1397 . You can have a look there, I provided multiple screenshots as well so if you still have any doubts we can discuss them.

**Comment by sownak** [comment]
Closing the issue as referenced in #1397
