### ISSUE TITLE
Indy-node docker build is failing

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#1396]
**Describe the bug**
Docker build of indy-node is failing 
https://hub.docker.com/repository/registry-1.docker.io/hyperledgerlabs/indy-node/builds/ffee351d-faf7-4f79-9679-99ab0d1f6bc5

```
epends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
Depends: python3-pympler (= 0.5) but 0.8 is to be installed
[91mE: Unable to correct problems, you have held broken packages.
[0m
Removing intermediate container cb384d2d73d4
The command '/bin/sh -c apt-get update -y && apt-get install -y indy-plenum=${indy_plenum_ver} indy-node=${indy_node_ver} python3-indy-crypto=${python3_indy_crypto_ver} libindy-crypto=${indy_crypto_ver} python3-pyzmq=${python3_pyzmq_ver}' returned a non-zero code: 100
```

**To Reproduce**
1. Go to 'platforms/hyperledger-indy/images/indy-node'
2. Run docker build as per the readme of the folder
3. The build fails

**Expected behavior**
Indy Node build should be successful.

**Environment (please complete the following information):**
 - OS: ubuntu
 - Version 0.8.0.0

**Comment by Dimbu-Afonso** [comment]
Issue seems to be related to packages dependencies that would need to be upgraded. Will have a look at the issue and test in the process. Adding this comment as a placeholder

**Comment by Dimbu-Afonso** [comment]
@sownak @suvajit-sarkar Indy-node build is now successful after fixing the package dependency issue. 
```
Step 22/22 : ENTRYPOINT ["/var/lib/indy/start-indy-node.sh"]
 ---> Using cache
 ---> d5ad7be60c73
Successfully built d5ad7be60c73
Successfully tagged hyperledgerlabs/indy-node:1.11.0
```
