### ISSUE TITLE
Test multiple channel creation from single network.yaml

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#1397]
### Description
As a developer I want to test multiple channel creation so that I can check if multiple channel creation from same network.yaml works.

### Acceptance Criteria
1. Test out and document and specific changes needed to support multiple channels in Fabric

**Comment by alvaropicazo** [comment]
Done with the testing. My scenario is the following: I declared two channels in the section channel; allchannel and secondchannel. I have used only an orderer organization and a peer organization (named 'calv', as a creator), that will be part of both channels. After the deployment, I executed the peer channel list command to see if the org 'calv' was part of both channels. This is the result:

![image](https://user-images.githubusercontent.com/76157062/114676346-7fd71280-9d09-11eb-8133-6f088935b504.png)

**Comment by alvaropicazo** [comment]
Had an scenario where two orgs (creator and joiner) will be part of two different channels. The network.yaml is the following:
![3_ch](https://user-images.githubusercontent.com/76157062/115407558-6abe2000-a1f0-11eb-9951-0ccf7ba48da8.png)
So it is expected to have calv in both channels and malv joining secondchannel.
After the deployment, in the cli pod of the peers of each organization, I executed peer channel list to check which channels was the organization part of:

![1_ch](https://user-images.githubusercontent.com/76157062/115407722-95a87400-a1f0-11eb-978d-0842a7553780.png)
![2_ch](https://user-images.githubusercontent.com/76157062/115407734-96d9a100-a1f0-11eb-838c-615e6ed2abfa.png)

Worked as expected.
