### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger-labs/blockchain-automation-framework#14]
In order to make BAF a welcoming community, where expectations are clear, we need a code of conduct document.  This is largely expected to borrow from / reference the Hyperledger [code of conduct](https://wiki.hyperledger.org/display/HYP/Hyperledger+Code+of+Conduct), but should still have a reference within this repository.

**Comment by sownak** [comment]
Closed with #88 and #89
