### ISSUE TITLE
Error while running Indy on minikube

### ISSUE THREAD

**Issue by vaibhavmittal215** [hyperledger-labs/blockchain-automation-framework#1410]
I am trying to follow these steps to set up a Hyperledger-Indy DLT network on minikube [Steps Link](https://blockchain-automation-framework.readthedocs.io/en/latest/developer/baf_minikube_setup.html). While running the Execute step, I am getting this error. Can you tell me what might be the cause of this error?
![Screenshot from 2021-04-23 02-28-05](https://user-images.githubusercontent.com/79312374/115784744-255e4600-a3dc-11eb-9769-cc579ba54045.png)

**Comment by sownak** [comment]
@vaibhavmittal215 This is a vault configuration issue. And minikube support is not longer provided by BAF team.

**Comment by vaibhavmittal215** [comment]
Thanks, I think you should either remove the minikube code from this repo or at least mention on the README that minikube is no longer supported.

**Comment by sownak** [comment]
It is mentioned in the release notes. https://github.com/hyperledger-labs/blockchain-automation-framework/releases/tag/v0.8.0.0
