### ISSUE TITLE
Is there plan to support Hyperledger Fabric 2.x with RAFT consensus?

### ISSUE THREAD

**Issue by edwardtam919** [hyperledger-labs/blockchain-automation-framework#1428]
**Is your feature request related to a problem? Please describe.**
See that the orderer for HF is still Kafka

**Describe the solution you'd like**
Support of RAFT for HF 2.x

**Describe alternatives you've considered**

**Additional context**

**Comment by arsulegai** [comment]
@edwardtam919 Kafka is deprecated for latest versions. It is Raft is the consensus algorithm supported for the ordering service cluster. Could you point the place where it says Kafka? It is highly likely to have been left out.

**Comment by edwardtam919** [comment]
I found all the config are Kafka, no RAFT. The documentation as well. No mention of RAFT.

![Screenshot 2021-04-28 at 7 22 48 PM](https://user-images.githubusercontent.com/82201342/116396049-76948c80-a857-11eb-98a9-0c82c4391b37.png)

**Comment by sownak** [comment]
@edwardtam919 Please do not raise queries as Issues, there is rocketchat to answer your queries. https://blockchain-automation-framework.readthedocs.io/en/latest/operations/fabric_networkyaml.html?highlight=RAFT
