### ISSUE TITLE
Failing on creating certificates in create/crypto roles

### ISSUE THREAD

**Issue by alvaropicazo** [hyperledger-labs/blockchain-automation-framework#1453]
**Describe the bug**
The deployment is getting stucked either on the create/crypto/orderer tasks or create/crypto/peer tasks (last ones actually get a code failure).

**To Reproduce**
1. Use current develop code version.
2. Run fabric 2.2.2 deploying a simple network, 1 peer org should be ok to reproduce the bug.

**Expected behavior**
The deployment can get stucked at create/crypto/orderer : Generate crypto material for organization orderers, or in create/crypto/peer, which won't create the certificates so when trying to use them in athe following roles, will get a no such file or directory error.
**Screenshots**

**Environment (please complete the following information):**
 - Fabric 2.2.2
 - Develop code version

**Comment by suvajit-sarkar** [comment]
Not able to reproduce the bug, need more information
