### ISSUE TITLE
Create ambassador tls secret in organization namespace

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1462]
### Description
As a developer I want to create the ambassador tls secret in the organization namespace instead of default namespace for corda enterprise and OS

(add more description and relevant links)

### Acceptance Criteria
1. Network deploys successfully without error
2. Ambassador tls secrets are create in org namespace
3. The services connect over tls

**Comment by pppazos** [comment]
I can work this
