### ISSUE TITLE
Docker updated file causing python error

### ISSUE THREAD

**Issue by vaibhavmittal215** [hyperledger-labs/blockchain-automation-framework#1471]
After the recent update in the docker file where the python version is explicitly mentioned to be 3.6, I got this error:
![Screenshot from 2021-05-11 02-38-19](https://user-images.githubusercontent.com/79312374/118896727-823f1480-b926-11eb-931b-35d04d1f96f4.png)

I am trying to create a sample Indy network. I followed [these](https://blockchain-automation-framework.readthedocs.io/en/latest/developer/baf_minikube_setup.html) steps to create the network except that I am creating the Kubernetes cluster on EKS. The elaborated steps that I followed are mentioned in this [issue](https://github.com/hyperledger-labs/blockchain-automation-framework/issues/1470).

For now, I found a way to bypass this error by adding a line into this yaml file
![python_change](https://user-images.githubusercontent.com/79312374/118897099-448ebb80-b927-11eb-93bc-ec8eb15f6287.png)

**Comment by sownak** [comment]
This should not be fixed like this, can be updated in the Dockerfile itself, isnt it?

**Comment by vaibhavmittal215** [comment]
You are saying that we can add this line in the Dockerfile itself??
Actually, I added this line here because this particular task was giving the error.

**Comment by sownak** [comment]
Yes, and raise a PR. That will solve this issue, right?
