### ISSUE TITLE
corda:4.4-linuxkit dockerhub image using corda 4.7

### ISSUE THREAD

**Issue by James-Ronayne** [hyperledger-labs/blockchain-automation-framework#1472]
**Describe the bug**
It looks like a corda 4.7 docker image was recently added to docker hub but it looks like in the process the corda:4.4-linuxkit image was also updated to corda 4.7

This means that the notary fails to start as configuration requirements changed between 4.4 and 4.7.

You can clearly see the 4.4-linuxkit tag is built using 4.7 here: <https://hub.docker.com/layers/hyperledgerlabs/corda/4.4-linuxkit/images/sha256-1d6008e3c43c5b2dab43d546ac6450b9f8097603b3be2685fa535ce8fcd0c5b3?context=explore>

**To Reproduce**
1. Pull the docker tag corda:4.4-linuxkit from dockerhub

**Expected behavior**
Docker image should be built with Corda 4.4

**Screenshots**
![image](https://user-images.githubusercontent.com/1560826/118956295-6142e780-b957-11eb-8e37-eda3ba8aedf7.png)

**Comment by sownak** [comment]
The Image has been rebuilt and uploaded on dockerhub
![image](https://user-images.githubusercontent.com/20537268/119135856-dfc28680-ba36-11eb-99ab-6602b6da2897.png)
