### ISSUE TITLE
Code cleanup of shared playbooks and roles

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1511]
### Description
As a I want to developer I want to refactor, remove unwanted code and unused versions from the platforms/shared folder

### Acceptance Criteria
1. Ensure shared molecule tests are cleaned as well and passes 
2. Ensure code Readme and comments are properly done

**Comment by pppazos** [comment]
changes applied:

- add default versions on shared roles and cleanup playbooks for:
- setup/kubectl : default in defaults/main.yaml to 1.16.3, can be override from playbook
- setup/helm default in defaults/main.yaml to v3.2.4, can be override from playbook
- setup/vault default in defaults/main.yaml to v1.7.0, can be override from playbook
- setup/aws-auth default in defaults/main.yaml to v1.10.3, can be override from playbook
- setup/ambassador version is locked in helm chart
