### ISSUE TITLE
Quorum molecule scenario ambassador-certs failing

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1527]
**Describe the bug**
The Quorum molecule scenario ambassador-certs is failing due to incorrect namespace creation and check.

**To Reproduce**
1. Go to platforms/quorum/configuration
2. Run molecule test scenario using the command : "molecule test -s ambassador-certs"
3. Scroll down to failed role

**Expected behavior**
The test scenario should pass

**Screenshots**
![image](https://user-images.githubusercontent.com/55580532/122038113-e43e4d00-cdf2-11eb-9ddc-6af4bf830651.png)

**Environment (please complete the following information):**
- NA

**Additional context**
Molecule tests are also failing because of this issue

**Comment by angelaalagbe** [comment]
I'll take this issue
