### ISSUE TITLE
Test DLT network deployment on Kubernetes v1.19

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1538]
### Description
As a deveIoper want to test DLT network deployments using BAF on Kubernetes version 1.19
DLT Networks to be tested as part of this issue are

- [x] Corda OS
- [x] Corda Ent.
- [x] HL Fabric 
- [x] HL Besu
- [x] Quorum
- [x] HL Indy

EKS v1.19 would be used for testing purpose

### Acceptance Criteria
1. Deployment successful with application endpoints tested

**Comment by suvajit-sarkar** [comment]
@pppazos can you have a look on this one

**Comment by pppazos** [comment]
I can take this one
