### ISSUE TITLE
Vault kv v2 support for Corda Opensource

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#1546]
### Description
As a developer I want to use v2 secret engine so that I can use the latest features

Updates needed to upgrade Vault to kv2:

1. Update secret path with v2 `vault secrets enable` to `vault secrets enable -version=2` in file `platforms/r3-corda/configuration/roles/setup/vault_kubernetes/tasks/main.yaml`
2. In the above file, update the policy for Access Control to include data like `"path \"{{ component_name }}/data/*\"`
3. Update role `setup/get_crypto` as the yaml output format has changed.
4. Command `vault kv get -format=yaml` will not fail if secrets do not exists, update ansible when conditions accordingly to check if the secret was deleted.

### Acceptance Criteria
1. Network deployment and API tests should be successful.

**Comment by kaverikhaneja** [comment]
I can take this issue.
