### ISSUE TITLE
Vault KV v2 support for Corda Enterprise

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#1547]
### Description
As a developer I want to use v2 secret engine so that I can use the latest features

Updates needed to upgrade Vault to kv2:

1. If not already done, manually enable separate secret path with v2 `vault secrets enable -version=2 -path=secretsv2 kv`
2. Update network.yaml with new path `secretsv2` in `vault.secret_path`
3. Update `platforms/r3-corda-ent/configuration/roles/setup/vault_kubernetes/tasks/main.yaml` policy templates to include data like `path "{{ vault_secret_path }}/data/***" {`
4. Replace all `vault write` which creates keys with `vault kv put`
5. Update role `setup/get_crypto` as the yaml output format has changed.
6. Command `vault kv get -format=yaml` will not fail if secrets do not exists, update ansible when conditions accordingly to check if the secret was deleted.
7. Replace all `vault delete` which deletes keys with `vault kv delete`

### Acceptance Criteria
1. Network deployment and API tests should be successful.

**Comment by angelaalagbe** [comment]
I'll take this
