### ISSUE TITLE
Separate Quorum node and tessera deployment

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1556]
### Description
As a developer I want to separate quorum node and tessera deployment

### Additional description
Follow the approach of BAF HL Besu, the separation was done in the PR #1540 

### Acceptance Criteria
1. Chart created for Tessera deployment
2. Automation roles and created to deployment instructions

**Comment by mgCepeda** [comment]
I'm going to work on this issue
