### ISSUE TITLE
Express API app for running smart contract endpoints in Besu

### ISSUE THREAD

**Issue by alvaropicazo** [hyperledger-labs/blockchain-automation-framework#1562]
As a developer I want to create an express API application which can communicate with the deployed smart contract in a besu network and be able to do private transactions via the endpoints exposed with this express application.

The related spike for this story is: #1537

### Acceptance Criteria

If deploying the supply-chain smart contract:

1. Register some products in the network via the endpoint exposed for that in particular.
2. Get the products via  the express API and check if they were registered correctly in the blockchain.

**Comment by kaverikhaneja** [comment]
I can work on this issue.

**Comment by kaverikhaneja** [comment]
As per ongoing testing, looks like the web3js-eea library is not compatible with our current version of Besu, for sending transactions. Will be trying web3js-quorum instead, for the same.

**Comment by kaverikhaneja** [comment]
This issue had following tasks  :

- Deploying a smart contract, sending private transactions on  HL-Besu.
- Creating an express app which can communicate with HL-Besu peers.
- The express app is able to communicate with the deployed smart contract and do private transactions via the endpoints exposed.

Findings:

- A smart contract was successfully deployed and private transactions were sent using the web3js-quorum library. [Web3js-quorum](https://besu.hyperledger.org/en/latest/Reference/web3js-quorum/#web3js-quorum) contains all the quorum.js and web3js-eea features in a single library. 
- EthSigner (transaction signing service) was also explored for the ethereum account management as HL-Besu doesn't support key management inside the client. While the EthSigner was able to pass requests to HL-Besu from the node environment, it seemed to be unsuitable to run on Kubernetes with service urls. Hence, currently, to carry out any ethereum account related tasks, we can use node address generated with `besu operator` command, as essentially a node address is same as the ethereum account address, which is created using the node private key.
- The Express app was deployed and was able to communicate with Besu nodes. The interaction with a deployed smart contract will be further developed and tested in this spike issue #1747
