### ISSUE TITLE
Fabric: Wait for ClusterRoleBinding supplychain-net-role-tokenreview-binding

### ISSUE THREAD

**Issue by hoang-innomizetech** [hyperledger-labs/blockchain-automation-framework#1567]
**Describe the bug**
I am new to BAF and I have been trying to deploy the sample network `network-fabricv2.yaml`. Currently, I am stuck at the task `Wait for ClusterRoleBinding supplychain-net-role-tokenreview-binding` and I have no idea why it occurs.

[ansible-logs.txt](https://github.com/hyperledger-labs/blockchain-automation-framework/files/6785527/ansible-logs.txt)

![image](https://user-images.githubusercontent.com/43955692/124945455-598aef80-e038-11eb-969d-27dd6670aeb3.png)

Has anyone encountered this issue yet? 

**Environment (please complete the following information):**
- OS: MacOS
- ansible [core 2.11.2]
- I run my Kubernetes cluster using VM https://github.com/LocusInnovations/k8s-vagrant-virtualbox
[ansible-logs.txt](https://github.com/hyperledger-labs/blockchain-automation-framework/files/6785477/ansible-logs.txt)

**Comment by sownak** [comment]
Please check https://blockchain-automation-framework.readthedocs.io/en/latest/operations/baf_verify.html and also rocketchat discussions before raising bugs.

**Comment by chaitanyakommoju** [comment]
was there any solution to this issue?

`Wait for ClusterRoleBinding supplychain-net-role-tokenreview-binding`

**Comment by sownak** [comment]
This is not an issue, it is waiting for the clusterrolebinding to be completed, please follow the verify guide if you are stuck at this stage and the playbook fails, then most likely the GitOps part is not working because you have wrong configuration in gitops section of network.yaml
