### ISSUE TITLE
Peer and order pods stuck at CrashLoopBackOff

### ISSUE THREAD

**Issue by hoang-innomizetech** [hyperledger-labs/blockchain-automation-framework#1569]
**Describe the bug**
I am using the sample network network-fabricv2-raft.yaml to deploy the HLF to Kubernetes EKS 1.19 on AWS, the peers and orderer pods are created but it cannot be started (there is only peer is running).

I tried to see the logs of error peer
`kubectl logs peer0-0 -n manufacturer-net --all-containers=true`

and here is the output
```[notice] 2021-07-15T04:42:09.566815Z nonode@nohost <0.324.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2021-07-15T04:42:09.567181Z nonode@nohost emulator -------- Error in process <0.32653.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}

[notice] 2021-07-15T04:42:14.567849Z nonode@nohost <0.324.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2021-07-15T04:42:14.568067Z nonode@nohost emulator -------- Error in process <0.32702.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}

2021-07-15 04:38:49.469 UTC [msp] getPemMaterialFromDir -> WARN 001 Failed reading file /etc/hyperledger/fabric/crypto/msp/signcerts/server.crt: no pem content for file /etc/hyperledger/fabric/crypto/msp/signcerts/server.crt
2021-07-15 04:38:49.469 UTC [main] InitCmd -> ERRO 002 Cannot run peer because error when setting up MSP of type bccsp from directory /etc/hyperledger/fabric/crypto/msp: Setup error: nil conf reference
Getting secrets from Vault Server: http://100.26.237.202:8200
Getting TLS certificates from Vault using key baf-dev-secret/crypto/peerOrganizations/manufacturer-net/peers/peer0.manufacturer-net/tls
Getting MSP certificates from Vault using key baf-dev-secret/crypto/peerOrganizations/manufacturer-net/peers/peer0.manufacturer-net/msp
Getting couch db credentials```

I am not sure why there is only one peer can start and run but the rest stuck at `CrashLoopBackOff`

There is no problem with vault connectivity and ca and ca-tools pods are running. The secrets have been pushed to vault server

**Expected behavior**
We should be able to deploy the network without any errors

**Screenshots**

![image](https://user-images.githubusercontent.com/43955692/125730687-0923a633-2f83-41bf-b988-b946b3378182.png)


**Environment (please complete the following information):**
 - OS: MacOS
 - HLF 2.2.0
 - Kubernetes: Client Version: v1.19.7 - Server Version: v1.19.8-eks-96780e
 - Vault: 1.7.3

**Comment by hoang-innomizetech** [comment]
I think the `MOUTH_PATH` environment variable is wrong on the deployment file `platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml`

```
- name: MOUNT_PATH
  value: /secret
```

I think it should be 
```
- name: MOUNT_PATH
  value: /var/hyperledger/orderer/crypto
```

**Comment by jagpreetsinghsasan** [comment]
@hoang-innomizetech 
The MOUNT_PATH set to secret is perfectly fine here(https://github.com/hyperledger-labs/blockchain-automation-framework/blob/358823dfcea856b5ac654dfe3e0e81102b8afa15/platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml#L128)

Then we later mount this volume (named as certificates, mentioned here(https://github.com/hyperledger-labs/blockchain-automation-framework/blob/358823dfcea856b5ac654dfe3e0e81102b8afa15/platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml#L206) on the actual path here(https://github.com/hyperledger-labs/blockchain-automation-framework/blob/358823dfcea856b5ac654dfe3e0e81102b8afa15/platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml#L230)

**Comment by hoang-innomizetech** [comment]
Yes, after a few debugging hours, I've figured out that the certificates cannot received from the CA servers, but the shell does not through error. I have to correct the dns names in the network file and redeploy. But I think we should figure out how can we catch error when running shell tasks. Currently, we are running multiple commends, it failed but the ansible still ignore that. We could see whether we can add `set -xeu` to some .sh file and also need to add more ways to catch error, especially using shell (maybe using command is better)

**Comment by jagpreetsinghsasan** [comment]
Can you tell on which specific task of Ansible role which got skipped because of some error in multi liner shell script?

**Comment by hoang-innomizetech** [comment]
Here is the task that failed but skipped by Ansible 

TASK [create/crypto/peer : Generate crypto material for organization orderers]

When I review the log, I saw an issue that the certificate is already registered. The DNS names in the network file might cause many confusion for users, so I think we should have a better documentation for configuring the network file.

FYI, currently, am getting another error when adding a new org to an existing network. I posted to chat at https://chat.hyperledger.org/channel/blockchain-automation-framework/thread/uKZP4TvTpxa5b9c2d

**Comment by jagpreetsinghsasan** [comment]
This task does not exist
![image](https://user-images.githubusercontent.com/56861721/126146081-acb0148f-fba9-4516-b9da-78e29d8495f5.png)


What you are referering to, exists in [here](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/358823dfcea856b5ac654dfe3e0e81102b8afa15/platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/common.yaml#L39)
create/crypto/orderer: Generate crypto material for organization orderers

**Comment by hoang-innomizetech** [comment]
Please check [here](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/358823dfcea856b5ac654dfe3e0e81102b8afa15/platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderer.yaml#L112)

**Comment by jagpreetsinghsasan** [comment]
> That;s what I said above, its under crypto/orderers. but your error message said create/crypto/peer. Its fine.

About the task itself, we are running the generate-crypto.sh script on the container of the pod, using kubectl exec command
Definitely, we need ways (triggers) so that we can trigger ansible roles/errors for the same.
Your suggestions around the same is highly valuable, as we are currently decoupling ansible from helm charts and are targeting to use ansible only for templatizing. During this, we have even more such instances, and triggers which can be captured in ansible are highly valued.

**Comment by jagpreetsinghsasan** [comment]
> That;s what I said above, its under crypto/orderers. but your error message said create/crypto/peer. Its fine.

About the task itself, we are running the generate-crypto.sh script on the container of the pod, using kubectl exec command
Definitely, we need ways (triggers) so that we can trigger ansible roles/errors for the same.
Your suggestions around the same is highly valuable in this regard.

**Comment by hoang-innomizetech** [comment]
The latest develop branch made change on the validateVaultResponse() function of the `certificates-init` container, so we cannot catch error response from CA server.

**Comment by jagpreetsinghsasan** [comment]
The error responses of the CA-server can be catched by checking logs of the ca container.
The validateVaultResposne( ) is improvised only for the certificates-init container, so it will not affect the CA-server logs.

**Comment by jagpreetsinghsasan** [comment]
Hi @hoang-innomizetech 
Is this bug valid anymore?

**Comment by hoang-innomizetech** [comment]
This issue might cause by invalid network configurations (DNS). I am happy to close this one. 

I also saw an issue with vault secret path. In some places we still write the vault secret into a hardcoded path instead of vaultPath from the network file i.e. [here](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/5861faa0fe7bd0ad15ad274e074e1f48ea310c1f/platforms/hyperledger-fabric/configuration/roles/create/chaincode/commit/tasks/write.yaml#L5)

**Comment by alvaropicazo** [comment]
Yes, we are aware of that and we are fixing it in this PR. #1571 .

Thanks @hoang-innomizetech
