### ISSUE TITLE
feat(fabric): ansible decoupling for setup/vault_kubernetes role

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1572]
### Description
As a developer, I want to decouple Ansible from BAF. This is achieved by moving the extra functionality from ansible to helm charts and use ansible only for templatizing purposes only.

This issue covers the change needed for setup/vault_kubernetes role

#### State of the deployment before running of the new role (subject to change, if required)
1. Auth path not set
2. Jwt reviewer token not set for the auth paths
3. Vault access control policies undefined for orgs
4. Vault role undefined
5. Docker pull credentials unset

#### State of the deployment after running the new role (subject to change, if required)
1. Auth path set
2. Jwt reviewer token extracted from each kubernetes cluster and set for the above set auth path
3. Vault access control policies created and written to vault
4. Vault auth role created and linked to respective service account, namespaces & vault access control policies
5. Docker pull credentials set as kubernetes secrets

### Acceptance Criteria
1. The setup/vault_kubernetes role should be modified in such a way that ansible is only used for templatizing purpose.
2. The previous and expected state of the deployment shall match the above description

**Comment by mgCepeda** [comment]
I'm going to work on this issue
