### ISSUE TITLE
feat(fabric): ansible decoupling for create/ca_server role

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1573]
### Description
As a developer, I want to decouple Ansible from BAF. This is achieved by moving the extra functionality from ansible to helm charts and use ansible only for templatizing purposes only.

This issue covers the change needed for create/ca_server role

#### State of the deployment before running of the new role (subject to change, if required)
1. Root CA certs not created
2. Ambassador certs for CA and thus corresponding k8s secret not created

#### State of the deployment after running the new role (subject to change, if required)
1. Root CA certs created and stored in vault
2. Ambassador certs for CA created and stored as k8s secrets along with a backup of them on vault

### Acceptance Criteria
1. The create/ca_server role should be modified in such a way that ansible is only used for templatizing purpose.
2. The previous and expected state of the deployment shall match the above description

**Comment by mgCepeda** [comment]
I will work on this issue
