### ISSUE TITLE
(fabric) BAD_REQUEST -- ConfigUpdate for channel '' but envelope for channel 'baf-custom'"

### ISSUE THREAD

**Issue by hoang-innomizetech** [hyperledger-labs/blockchain-automation-framework#1581]
**Describe the bug**
I am getting an error when adding a new peer org to an existing network. 

_TASK [setup/config_block/sign_and_update : updating the channel with the new configuration block]_

[update-channel-error.json.txt](https://github.com/hyperledger-labs/blockchain-automation-framework/files/6869565/update-channel-error.json.txt)

This is the network file I have used to deploy and add new org
[add-org-network-sample.yaml.txt](https://github.com/hyperledger-labs/blockchain-automation-framework/files/6869538/add-org-network-sample.yaml.txt)

**To Reproduce**
1. Deploy initial network with 3 orgs
2. Add new org to the above deployed network
3. See error

**Expected behavior**
We should able to add a new org to an existing network without any issue.

**Environment (please complete the following information):**
 - OS: MacOS
- Ansible:  2.11.2
- Fabric: 2.2.0
- BAF: latest master branch

I have viewed the envelop.json file and I saw that the "channel_id" in the config_update object is blank. I am not sure why
```sh
bash-5.0# cat baf-custom_update_in_envelope.json 
{
  "payload": {
    "header": {
      "channel_header": {
        "channel_id": "baf-custom",
        "type": 2
      }
    },
    "data": {
      "config_update": {
        "channel_id": "",
        "isolated_data": {},
        "read_set": null,
        "write_set": null
      }
    }
  }
}
```

**Comment by hoang-innomizetech** [comment]
I saw then running this task `TASK [setup/config_block/fetch : fetch and copy the configuration block from the blockchain]` we got an error relates to `jq` 

```"+ CURRENT_DIR=/opt/gopath/src/github.com/hyperledger/fabric/peer",
"+ echo 'installing jq '",
"+ apt-get install -y jq",
"./create_block.sh: line 8: apt-get: not found",
"+ echo 'installing configtxlator'",
"+ mkdir temp",
"+ cd temp/",
"+ wget https://github.com/hyperledger/fabric/releases/download/v2.2.0/hyperledger-fabric-linux-amd64-2.2.0.tar.gz",
"Connecting to github.com (140.82.121.4:443)",
"Connecting to github-releases.githubusercontent.com (185.199.111.154:443)",
"saving to 'hyperledger-fabric-linux-amd64-2.2.0.tar.gz'",
"hyperledger-fabric-l  14% |****                            | 10.3M  0:00:06 ETA",
"hyperledger-fabric-l 100% |********************************| 72.7M  0:00:00 ETA",
"'hyperledger-fabric-linux-amd64-2.2.0.tar.gz' saved",
"+ tar -xvf hyperledger-fabric-linux-amd64-2.2.0.tar.gz",
"+ mv bin/configtxlator ../",
"+ cd ../",
"+ rm -r temp",
"+ echo 'converting the channel_config_block.pb to channel_config.json using configtxlator and jq'",
"+ configtxlator proto_decode --input+ jq '.data.data[0].payload.data.config'",
" baf-custom_config_block.pb --type common.Block",
"+ echo 'adding new organization crypto material from config.json to the channel_config.json to make channel_modified_config.json'",
"+ jq -s '.[0] * {\"channel_group\":{\"groups\":{\"Application\":{\"groups\": {\"bank3MSP\":.[1]}}}}}' baf-custom_config.json ./config.json",
"+ echo 'adding anchor peer information to the block'",
"+ cat ./anchorfile.json",
"+ jq '.channel_group.groups.Application.groups.bank3MSP.values += {\"AnchorPeers\":{\"mod_policy\": \"Admins\",\"value\":{\"anchor_peers\": [-n' '{\"host\":\"peer0.bank3-net.mydomain.com\",\"port\":8443}]},\"version\": \"0\"}}' baf-custom_modified_config_without_anchorpeer.json",
"jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:",
".channel_group.groups.Application.groups.bank3MSP.values += {\"AnchorPeers\":{\"mod_policy\": \"Admins\",\"value\":{\"anchor_peers\": [-n                                                                                                                              ",
"jq: 1 compile error",
"+ echo 'converting the channel_config.json and channel_modified_config.json to .pb files'",
"+ configtxlator proto_encode --input baf-custom_config.json --type common.Config --output baf-custom_config.pb",
"+ configtxlator proto_encode --input baf-custom_modified_config.json --type common.Config --output baf-custom_modified_config.pb",
"configtxlator: error: Error decoding: error decoding input: error unmarshaling intermediate JSON: EOF",
"+ echo 'calculate the delta between these two config protobufs using configtxlator'",
"+ configtxlator compute_update --channel_id baf-custom --original baf-custom_config.pb --updated baf-custom_modified_config.pb --output baf-custom_update.pb",
"configtxlator: error: Error computing update: error computing config update: no channel group included for updated config",
"+ echo 'decode the channel_update.pb to json to add headers.'",
"+ jq .",
"+ configtxlator proto_decode --input baf-custom_update.pb --type common.ConfigUpdate",
"+ echo 'wrapping the headers arround the channel_update.json file and create channel_update_in_envelope.json'",
"+ jq .",
"+ cat baf-custom_update.json",
"+ echo '{\"payload\":{\"header\":{\"channel_header\":{\"channel_id\":\"baf-custom\", \"type\":2}},\"data\":{\"config_update\":{' '\"channel_id\":' '\"\",' '\"isolated_data\":' '{},' '\"read_set\":' null, '\"write_set\":' null '}}}}'",
"+ echo 'converting the channel_update_in_envelope.json to channel_update_in_envelope.pb'",
"+ configtxlator proto_encode --input baf-custom_update_in_envelope.json --type common.Envelope --output baf-custom_update_in_envelope.pb",
"+ mv baf-custom_config_block.pb baf-custom_config_block_old.pb",
"+ cd /opt/gopath/src/github.com/hyperledger/fabric/peer"```

**Comment by hoang-innomizetech** [comment]
I have reviewed the generated file `platforms/hyperledger-fabric/configuration/build/channel-artifacts/baf-custom-anchorfile.json` and I saw that we have invalid value, not sure why -n also written to the file i.e.  _-n {"host":"peer0.bank3-net.baf.mydomain.com","port":8443}_

**Comment by hoang-innomizetech** [comment]
I have temporarily removed `-n` option when writing data to the .json file as I mentioned above and this issue is fixed. But I am getting another error when running the CLI to join the channel

_Error: genesis block file not found open baf-custom.block: no such file or directory_

Run this command in the CLI pod of the new org

```sh
peer channel fetch 0 baf-custom.block -o orderer1.baf.mydomain.com:8443 -c baf-custom --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt
```

And we are getting the below error
`Error: can't read the block: &{FORBIDDEN}`

Have anyone able to add a new org to the existing RAFT network?

**Comment by sownak** [comment]
We have always added new org in RAFT network. Are you sure a channel id with a - is acceptable in Fabric?

**Comment by hoang-innomizetech** [comment]
Yes, I am sure that the channel is working with the existing peers, just had an issue with the new peer and I have no idea why it doesn't work. We are able to deploy the network and chaincode without any issues

**Comment by sownak** [comment]
@hoang-innomizetech I have executed the steps for this bug and unable to reproduce. The issue here seems that you are using MacOS for the ansible controller, whereas we use ubuntu. All our code is tested on ubuntu and hence we provide a baf-build docker container to be used as the ansible controller. These issues seem to be because of MacOS as we do not test on MacOS. We have already started changes to use less of Ansible and more of Helm for all Fabric operations, but until that is done I suggest you use the baf-build docker container as Ansible controller.

**Comment by hoang-innomizetech** [comment]
@sownak We now use docker build to run the deployment, we can deploy the network, but when we try to add a new org to an exiting network (same configuration above), we now we are getting a different error

`Error: genesis block file not found open bafcustom.block: no such file or directory`

**Comment by sownak** [comment]
This looks like your genesis block is not getting downloaded, guess you have to debug yourself as we do not have the logs of what happened before this step.
