### ISSUE TITLE
Verify and fix documentation formatting and alignments 

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1623]
### Description
As a developer I want to verify and fix `readthedocs` documentation formatting and alignments.

### Additional Information
Link to the documentation : https://blockchain-automation-framework.readthedocs.io/en/develop/

### Acceptance Criteria
1. Formatting and Alignments fixed
2. Docs builds successfully
3. Changes done of develop branch

**Comment by nikhilagolla** [comment]
I will work on this

**Comment by nikhilagolla** [comment]
There are no changes. Everything is fine.
