### ISSUE TITLE
[Quorum] Update quorum certificate paths documentation

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1637]
**Description**
As a developer, I want to update the quorum certificate paths located here
https://blockchain-automation-framework.readthedocs.io/en/latest/architectureref/certificates_path_list_quorum.html

**Acceptance Criteria**
1. Update the docs to reflect the new certificates which are also pushed to the vault.

**Comment by kaverikhaneja** [comment]
I can take this issue.
