### ISSUE TITLE
[fabric] Use vault access policies from the configmaps 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#1657]
### Description
As a developer, I want to access the vault access policies as configmaps, mount the configmaps in the container and then pass them as payload for the vault put commands (using curl)

Currently the payload is created by directly writing it into payload.json as [here](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/830f4bca24e2783fcd83b49b5bd4eeab45f9da97/platforms/hyperledger-fabric/charts/vault_kubernetes/templates/job.yaml#L120)
![image](https://user-images.githubusercontent.com/56861721/132485069-78d97519-deef-425f-8069-90ec64046d14.png)

Helpful links (In the below example, we have created a configmap for a tessera config file and used it in the chart)
[configmap](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/830f4bca24e2783fcd83b49b5bd4eeab45f9da97/platforms/quorum/charts/node_tessera/templates/configmap.yaml#L13)
[usage in chart](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/830f4bca24e2783fcd83b49b5bd4eeab45f9da97/platforms/quorum/charts/node_tessera/templates/deployment.yaml#L49)

### Acceptance Criteria
1. The access control policies for vault should be created in configmap and fetched from there for usage within the container(s).

**Comment by mgCepeda** [comment]
I will work on this issue
