### ISSUE TITLE
Indy: Create Namespace Ansible role

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#17]
Prepare an Ansible role which creates all organizations' namespaces by using a K8S component role - needs the creation of the K8S namespace component template. Add the new role to the main deploy_network.yaml Indy playbook.

Have a look at 

[https://innersource.accenture.com/projects/BLOCKOFZ/repos/blockchain-automation-framework/browse/platforms/hyperledger-fabric/configuration/roles/k8_component/tasks/main.yaml]

[https://innersource.accenture.com/projects/BLOCKOFZ/repos/blockchain-automation-framework/browse/platforms/hyperledger-fabric/configuration/roles/k8_component/templates/namespace_component.tpl]

**Comment by juraj-durech** [comment]
Closed by #67
