### ISSUE TITLE
Create the Helm charts for Zone Service

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1735]
### Description
As a developer I want to create Zone service for the corda network

https://docs.r3.com/en/platform/corda/1.5/cenm/zone-service.html
https://github.com/corda/cenm-deployment

### Acceptance Criteria
1. Create the helm charts
2. Manual installation of the helm chart deploys Zone service

**Comment by surabhi-dudhediya** [comment]
I will work on this issue
