### ISSUE TITLE
Dockerfile for "Faber" university and "Alice" student

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#174]
### Description
As a developer I want to create a dockerfile for aries-agent so that I can deploy the Indy sample application using BAF

For Faber : change code for ability to use inserted seed
For Alice : no changes from original - just build an image

### Acceptance Criteria
1. Dockerfile to build image for Faber and Alice is created.
2. Both images are built and stored in docker hub

**Comment by blefevre** [comment]
Work on this (along with #175 and #176) is being postponed due to the deprecation of the Hyperledger Indy Agent Demo.
