### ISSUE TITLE
Spike: Integration of Auth, Gateway and Zone services with cenm core service

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1744]
### Description
As a developer I want to integrate Auth, Gateway and zone services with the core cenm services

### Acceptance Criteria
TBD

**Comment by surabhi-dudhediya** [comment]
I will work on this issue

**Comment by suvajit-sarkar** [comment]
Integration of auth, zone and gateway was successfully with the network deployed using BAF.

### Outcomes:

1. Idman, Signer and networtmap configs and charts needs to be modified for auth and zone integration
2. Gateway service endpoints needs to be externally exposed for UI access.

Issue #1764 is created to modify to required charts for complete automation.
