### ISSUE TITLE
Create Helm chart of "Faber" university

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#175]
### Description
As a developer I want to create "Faber" university helm chart so that I can deploy it on a kubernetes cluster using BAF.

Prerequisites:
1. Indy nodes should be already running on Kubernetes
2. Indy agent should be able to get the node ledger

### Acceptance Criteria
1. Helmchart created
2. Documentation created

**Comment by VladimirDzamba** [comment]
Helm Chart is created and tested on Minikube. I created init container for getting endorser's seed from vault and store into volume from where the main container read and put to environment variable. Seed from file is removed after put as environment variable.
