### ISSUE TITLE
Remove hardcoded key credentials from gateway and zone chart

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1753]
### Description
As a developer I want to use the key credentials from vault rather than having it hard-coded or passed as values

### Acceptance Criteria
1. the int-certificate container should fetch the credentials for the required keystores and truststores
3. All hard coded key credentials are removed from the chart

**Comment by surabhi-dudhediya** [comment]
i will work on this issue

**Comment by nikhilagolla** [comment]
I will work on this issue
