### ISSUE TITLE
Quorum: Ansible role to create crypto for RAFT

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#180]
### Description
As a developer I want to create crypto materials for RAFT so that I can deploy Quorum using BAF with RAFT consensus.
#### Pre-requisites
Add two new roles to install geth and bootnode.
Steps:
1. Check if geth/bootnode is already installed, if yes, skip.
2. If no, then from build directory `git clone https://github.com/jpmorganchase/quorum.git`
3.  From `quorum` directory, execute `make geth` and `make bootnode`, depending on which binary you are installing.
4. Move geth and/or bootnode binary from quorum/build/bin/ to defined bin directory.

#### Steps for RAFT crypto
1. For each org, first check Vault if the nodekey crypto exists. If exists, skip all following steps. 
2. If not, then create a node directory `mkdir <node name>`
3. Then `bootnode -genkey <node name>/nodekey`
4. Step to generate enode URL for this node (to add in static-nodes.json) `bootnode --nodekey=<node name>/nodekey --writeaddress > <node name>/enode`
5. Step to create a new geth account and keystore
  a) create a file called password to store the passphrase `echo {{peer.geth_passphrase}} >> password`
  b) `geth account new --datadir <node name> --password password`
  c) `cp <node name>/keystore/* <node name>/keystore.json`
6. Put Crypto in Vault
`vault kv put secret/<namespace>/crypto/<node name>/quorum nodekey="$(cat <node name>/nodekey)" keystore="$(cat <node name>/keystore.json)" db_user="demouser" db_password="password" gethpassword="$(cat password)"`

### Acceptance Criteria
1. All pre-requisites installed for RAFT crypto generation.
2. Crypto generation is idempotent i.e. generate new crypto if it does not exist.
3. Crypto is visible in Vault at path secret/<namespace>/crypto/<peername>/quorum.

**Comment by jagpreetsinghsasan** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/56861721/73067877-c7d50400-3ecf-11ea-92d2-ea93e1e0bb73.png)

**Comment by sownak** [comment]
Closed as per #268
