### ISSUE TITLE
Indy: Ansible role for Domain genesis

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#19]
Create an Ansible role, which retrieves the DIDs and verification keys for all trustees and stewards on the genesis network, assembles the Domain genesis transaction file, creates the Domain genesis config map values (Helm release) for all organizations and pushes them to the respective Git locations. Also, please add this role to the Indy deploy-network playbook.

**Comment by juraj-durech** [comment]
Closed by #118
