### ISSUE TITLE
Create Azure storage class for Corda Network

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#192]
### Description
As a developer I want to create Azure storage class so that the automatic deployment and testing of BAF for Corda network on Azure Kubernetes Service can be done.

**Comment by suvajit-sarkar** [comment]
Removed from release 0.4.0.0, as it will done based on client demand

**Comment by sownak** [comment]
new storage class addition is an operational guide now and is published at https://blockchain-automation-framework.readthedocs.io/en/latest/operations/adding_new_storageclass.html
