### ISSUE TITLE
Create Google storage class for Fabric network

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#194]
### Description
As a developer I want to create Google storage class so that the automatic deployment and testing of BAF for Fabric network on Google Kubernetes Service can be done

**Comment by suvajit-sarkar** [comment]
Removed from release 0.4.0.0, as this would be done based on client demand

**Comment by sownak** [comment]
Adding new storage class is documented at  https://blockchain-automation-framework.readthedocs.io/en/latest/operations/adding_new_storageclass.html
