### ISSUE TITLE
Running BAF from desktop modifies global git configs

### ISSUE THREAD

**Issue by maniankara** [hyperledger-labs/blockchain-automation-framework#205]
**Describe the bug**
1. Running BAF from desktop modifies global git configs.
The scripts run `git config --global ...` which modifies the desktops git configs also for other projects.
2. No ways to configure git's `user.email` its hard coded to `baf@accenture.com`

**To Reproduce**
1. Run `git config -l |grep user` in terminal 1 for a random project.
2. Open another terminal and run
`ansible-playbook -i hosts  deploy-network.yaml -e "@./network-fabricv2.yaml"`
3. Repeat 1
**Expected behavior**
The settings should be the same from 1 (above) as before
**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 0.3.00 (a3a0e46030a85f85da6a1cf19828526a669c8c71)

**Comment by sownak** [comment]
closed as per #206
