### ISSUE TITLE
Adding an option to make anchor peers, non anchor peers

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#233]
### Description
As a developer I want to provide an option to have defined number of non anchor peers

**Comment by jagpreetsinghsasan** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/56861721/72785753-ec23ad00-3c51-11ea-90cf-3809483758b1.png)

**Comment by sownak** [comment]
Closed as per #256
