### ISSUE TITLE
Indy: Test BAF Indy on AWS EKS

### ISSUE THREAD

**Issue by juraj-durech** [hyperledger-labs/blockchain-automation-framework#251]
As a user I want to use BAF Indy on AWS EKS, once K8S 1.16 is available on AWS.

AWS is currently just on 1.14
https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html
https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/
https://github.com/aws/containers-roadmap/issues/380

**Comment by suvajit-sarkar** [comment]
AWS EKS now supports k8s 1.16, prioritizing the issue from release 0.6, which would cover upgrading the k8s on AWS to 1.16 and test indy on it.
