### ISSUE TITLE
Indy: Ansible role to setup endorsers

### ISSUE THREAD

**Issue by juraj-durech** [hyperledger-labs/blockchain-automation-framework#252]
### Description
As a user I want to be able to add all endorser identities from the network.yaml to the ledger using respective admin identities (trustee / steward). This Ansible role should use the common create identity Ansible role and be called from the main deploy network playbook.

**Comment by himanshulalarya** [comment]
> ### Description
> As a user I want to be able to add all endorser identities from the network.yaml to the ledger using respective admin identities (trustee / steward). This Ansible role should use the common create identity Ansible role and be called from the main deploy network playbook.

>- This story requires to setup endorsers 
- while looping through the network yaml it will use the 'WHO CREATES WHO' logic to select the admin identity
and loop in through endorsers and send the selected parties (admin and new identity to be added) to helm release template creation task

After every template generation for selected parties the generated file will be pushed into the git repository.
Make just one git push per admin organisation.

**Comment by juraj-durech** [comment]
Closed vi #273
