### ISSUE TITLE
Ambassador is not created properly when running Indy deployment.

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#260]
**Describe the bug**
Ambassador is not created properly when running Indy deployment. The Ambassador service has errors and the Ambassador pods keep getting deleted.
Ambassador service does not get a public IP.

**To Reproduce**
1. Edit the samples/network-indyv3.yaml according to configuration
2. execute ansible-playbook site.yaml -e "samples/network-indyv3.yaml"
3. Execution continues but Ambassador is not working properly.

**Expected behavior**
Ambassador service should get a public IP address. And the pods of ambassador should not keep restarting.

**Screenshots**
Error for Ambassador Pods:
![image](https://user-images.githubusercontent.com/20537268/72906490-35dfc680-3d2a-11ea-8401-75eb1dc9125d.png)

**Additional context**
It seems that the Ambassador changes for using an EIP is done with the assumption that there will be only one Subnet, but in usual cases where the cluster is across multiple AZ, there are subnets per AZ, and hence Ambassador fails because the number of EIP should be same as the number of Subnets.

**Comment by juraj-durech** [comment]
Yes, the assumption was one public IP address per organisation => one public subnet => one AZ. We'll add a separate config parameter for organisation public IPs to support clusters that span multiple AZs.
