### ISSUE TITLE
Playbook fails to get ClusterRoleBinding authority-authority-trustee-vault-auth-role-binding even when it has been created

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#261]
**Describe the bug**
Playbook fails to get ClusterRoleBinding authority-authority-trustee-vault-auth-role-binding even when it has been created

**To Reproduce**
1. Edit the samples/network-indyv3.yaml according to configuration
2. execute ansible-playbook site.yaml -e "samples/network-indyv3.yaml"
3. Execution fails at "Wait for ClusterRoleBinding authority-authority-trustee-vault-auth-role-binding" after 20 retries.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/20537268/72909138-70e3f900-3d2e-11ea-979d-ea0ccb76e180.png)
The above fails even though the rolebinding is there
![image](https://user-images.githubusercontent.com/20537268/72909202-8527f600-3d2e-11ea-97a2-484ff50b7272.png)

**Additional context**
There seems to be a mismatch as how the check/k8s_component role is being used in the Indy code.

**Comment by juraj-durech** [comment]
@sownak I wasn't able to replicate the bug, can you please specify what kind of mismatch you have found in the code?

**Comment by sownak** [comment]
This seems to be an issue with Openshift cluster. This issue does not with usual EKS cluster.
The mismatch for example is:
1. using namespaces for Clusterrolebinding (I don't think clusterrolebindings are namespace specific)
2. check/k8_component is used in "waiting" but not for all the waits (which is okay I guess, in hindsight)

**Comment by sownak** [comment]
Also a general comment, a lot of anshible shell module has been used, and also a lot of bash script in this module has been used, which fails because default shell is sh.

**Comment by sownak** [comment]
Openshift is not in the recent roadmap hence this issue is closed.
