### ISSUE TITLE
Ansible fails at TASK [setup/vault_kubernetes : Write reviewer token for Organizations] 

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#265]
**Describe the bug**
Ansible fails at TASK [setup/vault_kubernetes : Write reviewer token for Organizations] 
This is because the kubernetes.context is not used, instead the context is assumed to be "kubernetes". This would not work if the Cluster Context is not kubernetes.

**To Reproduce**
1. Edit the samples/network-indyv3.yaml according to configuration
2. execute ansible-playbook site.yaml -e "samples/network-indyv3.yaml"
3. Execution fails when at the vault_kubernetes role.

**Expected behavior**
Execution to continue and update Vault with new key/value.

**Screenshots**
![image](https://user-images.githubusercontent.com/20537268/73064871-19fb3280-3e9a-11ea-841d-879740abbd7f.png)

**Comment by juraj-durech** [comment]
Closed via #307
