### ISSUE TITLE
Unable to mount volumes for flux volume pods on AKS

### ISSUE THREAD

**Issue by rahultoraskarr** [hyperledger-labs/blockchain-automation-framework#266]
Pods remain in "ContainerCreating" state. Kubernetes is not able to attach persistent volume to flux pods. 
Also, no PV/PVCs are created on the cluster.

![image](https://user-images.githubusercontent.com/19419595/73066552-534c9600-3ecc-11ea-88b2-14bc99d71bc7.png)

![image](https://user-images.githubusercontent.com/19419595/73066500-2b5d3280-3ecc-11ea-97b1-f33cbd721f8c.png)

**Comment by sownak** [comment]
This seems to be Kubernetes cluster configuration issue, and this is a flux pod, BAF does not maintain Flux.

**Comment by sownak** [comment]
This issue was because of permission issue on the private key file as a result of which Flux was not able to create the git-key. Not a BAF issue.
