### ISSUE TITLE
authority-baf-ac-auth-job and authority-authority-trustee-auth-job fails because kubernetes_url is empty

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#267]
**Describe the bug**
authority-baf-ac-auth-job and authority-authority-trustee-auth-job fails because kubernetes_url is empty

**To Reproduce**
1. Edit the samples/network-indyv3.yaml according to configuration
2. execute ansible-playbook site.yaml -e "samples/network-indyv3.yaml"
3. authority-baf-ac-auth-job and authority-authority-trustee-auth-job fails and goes into crashloopbackoff
4. Playbook execution fails

**Expected behavior**
The auth-jobs should be completed and playbook execution should continue.

**Additional context**
"Get the kubernetes server url" is not giving the correct output.

**Comment by juraj-durech** [comment]
Closed via #307
