### ISSUE TITLE
Indy: Create the Helm Chart for indy-key-mgmt Identity generation job

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#29]
Prepare a job Helm Chart using the indy-key-mgmt Docker image which will obtain a vault token using a K8S service account token and then will generate Identity crypto (run the script in the idy-key-mgmt Docker image).

**Comment by juraj-durech** [comment]
Fixed by #50

**Comment by juraj-durech** [comment]
#50 reverted via #52, fixed via #53
