### ISSUE TITLE
Support for anchor peers for newly added organisation in fabric network

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#308]
### Description
As a developer I want to add anchor peer information to the channel so that non-anchor peers of a newly added org. becomes anchor peers
1. Generate the json configuration for the anchor peers of the new Org.
2. Fetch the channel block 
3. Convert the channel block into json
4. Add anchor peer details to the json file using configtxlator
5. Convert the json file back to protobuf
6. Calculate the delta between the 2 protobuf configs
7. Convert protobuf back to json
8. Wrap the update between the header
9. Convert it back to protobuf
10. Sign the block from admin 
11. Update the channel with this information

### Acceptance Criteria
1. Anchor peer information is added into the channel

**Comment by sownak** [comment]
Closed as per #313
