### ISSUE TITLE
Indy: Store identity crypto in Vault without bootstrap

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#31]
Remove the bootstrap suffixes from Indy crypto in Vault, which affects:

1) Identity crypto generation in indy-key-mgmt (probably Vault upload)

2) Getting the crypto in indy-node init container (the from Vault path is without bootstrap but the filename should still have bootstrap)

**Comment by juraj-durech** [comment]
Closed by #216
