### ISSUE TITLE
Add new org playbook for Hyperledger Fabric doesn't wait for peer to come up

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#311]
**Describe the bug**
While running the playbook add-organization.yaml located at platforms/hyperledger-fabric/configuration, the playbook doesn't have checks in place which are responsible for peer to come up. 
The role setup/config_block/sign_and_update should first check if the peer pods are up, then only proceed with the tasks.
As currently the checks are not present, the playbook can show inconsistent behaviour and the 'join-channel' job can run even before the peer is up and running.

**Comment by sownak** [comment]
Closed as per #322
