### ISSUE TITLE
Add new organization playbook doesnt setup the environment prerequisites

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#312]
The playbook which adds organization to the existing network in Hyperledger-Fabric and R3 Corda platform doesn't setup the prerequisite environment setup (as site.yaml in shared/configuration folder does). This is needed if the new organization is on a different cluster.

**Comment by sownak** [comment]
Please use the bug report format when creating bugs.

**Comment by sownak** [comment]
Closed as per #322
