### ISSUE TITLE
Quorum App: Update Container 

### ISSUE THREAD

**Issue by jane-b-lee** [hyperledger-labs/blockchain-automation-framework#326]
### Description
As a participant of the blockchain network I want to change some parameters for a container so that the change is tracked in the blockchain.
Updates a container on the ledger.
Used for updating health data or metadata.
Implement the transaction to update a trackable on the ledger.
A trackable is defined as a container.

The transaction should accept:
health: String
misc: Map<String, any>
trackingID:String
counterparties : String[]

Then update Trackable on the blockchain with: The supplied health, and misc.

Given that:
Our Identity is in the participants list.
Our Identity is the current custodian.
Related Corda transaction: Commands.UpdateProduct

### Acceptance Criteria
1. Follow Solidity coding standards
2. Only the current custodian can update the data.

**Comment by jane-b-lee** [comment]
@sownak

**Comment by egshankle** [comment]
This story can be removed, the only container property that can be updated is custodian.  That's covered under https://github.com/hyperledger-labs/blockchain-automation-framework/issues/286.

**Comment by sownak** [comment]
@egshankle Can't we update the container "Health"

**Comment by sownak** [comment]
Closed as this is not implemented in other Platforms
