### ISSUE TITLE
Vault auto-unseal with AWS KMS

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#354]
Use AWS KMS to auto-unseal Vault server when started/restarted. This ensures that the Vault unseal key(s) are not stored in plaintext on a machine, rather are stored in AWS KMS.

**Comment by uyenle57** [comment]
Hi @jagpreetsinghsasan / @suvajit-sarkar, can you guys please provide more info in the description for this task?
 Thanks.

**Comment by uyenle57** [comment]
Vault integration with AWS auto-unseal / KMS is implemented by following this tutorial https://learn.hashicorp.com/vault/operations/ops-autounseal-aws-kms#step-2-test-the-auto-unseal-feature.

Current Vault config file is as follows:

```
disable_cache = true
disable_mlock = true
ui = true
log_level = "Debug"

storage "file" {
    path = "${local.mount_point}"
}

listener "tcp" {
    address = "0.0.0.0:${var.vault_port}"
    tls_disable = 1
}
      
seal "awskms" {
    region = "${var.aws_region}"
    access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    kms_key_id = "${aws_kms_key.vault.key_id}"
}
```

So now, if the Vault servers/instances are restarted, after running `vault init`, Vault will be automatically unsealed.

**Comment by sownak** [comment]
This has been implemented in the infrastructure code, no changes in the BAF code.
