### ISSUE TITLE
Docs: python openshift module dependency

### ISSUE THREAD

**Issue by Henni** [hyperledger-labs/blockchain-automation-framework#399]
Ansible's k8s module requires the openshift python package (>= 0.6).
This should be mentioned in the documentation (probably in the prerequisites)

**Comment by Roshan13046** [comment]
I would like to fix this issue. Can I work on it?

**Comment by Roshan13046** [comment]
> Ansible's k8s module requires the openshift python package (>= 0.6).
> This should be mentioned in the documentation (probably in the prerequisites)

Please share the doc link.

**Comment by sownak** [comment]
@Roshan13046  Yes sure. All docs are in docs folder, you may have to find all the files that refer openshift and update

**Comment by Roshan13046** [comment]
> @Roshan13046 Yes sure. All docs are in docs folder, you may have to find all the files that refer openshift and update

Any specific keyword to search in all files that refer openshift and update.

**Comment by sownak** [comment]
> > @Roshan13046 Yes sure. All docs are in docs folder, you may have to find all the files that refer openshift and update
> 
> Any specific keyword to search in all files that refer openshift and update. or any probable folders in doc section where I can find the files related to it.

Search for "openshift"
