### ISSUE TITLE
Spike: Hyperledger Besu provisioning

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#423]
### Description
As a developer I want to explore Hyperledger Besu so that it can be used as a DLT platform for BAF

https://www.hyperledger.org/projects/besu

**Comment by lakshyakumar** [comment]
[Besu Spike.pdf](https://github.com/hyperledger-labs/blockchain-automation-framework/files/4305494/Besu.Spike.pdf)

**Comment by sownak** [comment]
@lakshyakumar Please create the relevant Issues and then close this ticket.
