### ISSUE TITLE
Integration test of Quorum chaincodes 

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#426]
### Description
As a developer I want to run supplychain postman tests so that I can automate integration testing for Quorum

### Acceptance Criteria
1. Tests from examples\supplychain-app\tests should run successfully for Quorum
2. A new environment file is added for Quorum local test

**Comment by deepakkumardbd** [comment]
On testing the quorum application using the environment that is appQuorumLocalEnv.txt attached here, we got the following  output attached below.

[appQuorumLocalEnv.txt](https://github.com/hyperledger-labs/blockchain-automation-framework/files/4337547/appQuorumLocalEnv.txt)



![image](https://user-images.githubusercontent.com/57094817/76745768-70029d00-679c-11ea-9d7f-b1c155528927.png)

**Comment by suvajit-sarkar** [comment]
A bug needs to be created to resolve the API issues faced on testing using the environment values
