### ISSUE TITLE
Implement Linuxkit images for Corda Doorman

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#45]
Follow instructions to create doorman image

[https://innersource.accenture.com/projects/BLOI/repos/platform-kubernetes-corda/|https://innersource.accenture.com/projects/BLOI/repos/platform-kubernetes-corda/browse/charts/doorman/templates/deployment.yaml)]

From ambassador branch

Acceptance Criteria:
 # Create and upload image into docker registry. 
 # Update readme/readthedocs for building image.

**Comment by juraj-durech** [comment]
Closed by #68
