### ISSUE TITLE
Implement RAFT Consensus for Fabric

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#46]
As a user I want to use RAFT Consensus for my Fabric network so that I have a choice of consensus mechanisms.

This is a stretch goal if Fabric 1.4.1 is implemented.

### Acceptance Criteria:
 1. Add RAFT as another consensus mechanism
 2. Provide choice of consensus mechanism in network configuration.
 3. Create or update charts as necessary.
 4. Test deployment on cluster using GitOps.

**Comment by sownak** [comment]
Priority.

**Comment by jagpreetsinghsasan** [comment]
The current supplychain chaincode doesnt work.
So I installed fabcar chaincode to test the network.
I am attaching the screenshots of the query regarding the same

**Comment by jagpreetsinghsasan** [comment]
![alpha](https://user-images.githubusercontent.com/56861721/77397179-1d903480-6dcb-11ea-90ac-915ad4727ee1.PNG)
![beta](https://user-images.githubusercontent.com/56861721/77397187-21bc5200-6dcb-11ea-9657-afaf0d2c32ec.jpg)

**Comment by jagpreetsinghsasan** [comment]
To validate network I performed the following steps
1. Setup Fabric network using BAF and RAFT
2. Install 2 peer cli, one of each peer of the org (There are 2 orgs in my network.yaml with one peer in each org)
3. For peer0 of org1, perform the following steps in its cli
curl https://raw.githubusercontent.com/hyperledger/fabric-samples/release-1.4/chaincode/fabcar/go/fabcar.go > fabcar.go
mkdir -p /opt/gopath/src/github.com/chaincode
cp fabcar.go /opt/gopath/src/github.com/chaincode
peer chaincode install -n fabcar -v 1.0 -p github.com/chaincode

vault read secret/crypto/ordererOrganizations/sj-net/orderers/orderer3.sj-net/tls (get ca.crt) and store it as orderer.pem

peer chaincode instantiate -o orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443 --tls --cafile /opt/gopath/src/github.com/chaincode/orderer.pem -C allchannel -n fabcar -v 1.0 -c '{"Args":["Init"]}' -P ""

vault read secret/crypto/peerOrganizations/cj-net/peers/peer0.cj-net/tls   (get ca.crt) and store it as peer.pem

peer chaincode invoke  --tls true -o orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443 --tls --cafile /opt/gopath/src/github.com/chaincode/orderer.pem -C allchannel -n fabcar  --peerAddresses peer0.cj-net.hf.dev.aws.blockchaincloudpoc-develop.com:8443 --tlsRootCertFiles /opt/gopath/src/github.com/chaincode/peer.pem -c '{"Args":["initLedger"]}'


peer chaincode query -C allchannel -n fabcar -c '{"Args":["queryAllCars"]}'

4. For peer0 of org2, perform the following steps in its cli
curl https://raw.githubusercontent.com/hyperledger/fabric-samples/release-1.4/chaincode/fabcar/go/fabcar.go > fabcar.go
mkdir -p /opt/gopath/src/github.com/chaincode
cp fabcar.go /opt/gopath/src/github.com/chaincode
peer chaincode install -n fabcar -v 1.0 -p github.com/chaincode

peer chaincode query -C allchannel -n fabcar -c '{"Args":["queryAllCars"]}'

**Comment by jagpreetsinghsasan** [comment]
Created the bug to fix chaincode #488
