### ISSUE TITLE
Test Fabric 1.4.4 network deployment on the feature/fabric2.0 branch

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#461]
### Description
As a developer I want to test that Fabric 1.4.4 runs from the fabric2.0 feature branch so that we can announce backward compatibility.

### Acceptance Criteria
1. Orderer, peers and anchor peers should successfully run using network.version: 1.4.4 on fabric2.0 branch.
2. Any bugs found should be reported.

**Comment by himanshulalarya** [comment]
Ca, catools, orderer and peers are up but it is failing at create channel
So inorder to check the validity of the network yaml with the code of develop branch, it works fine.
Created a bug #485
