### ISSUE TITLE
Test Fabric 1.4.4 chaincode deployment on the feature/fabric2.0 branch

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#462]
### Description
As a developer I want to test that Fabric 1.4.4 chaincodes run from the fabric2.0 feature branch so that we can announce backward compatibility.

### Acceptance Criteria
1. Supplychain chaincode should successfully install and instantiate on Fabric 1.4.4 network created from fabric2.0 branch.
2. Any bugs found should be reported.
3. Supplychain API test should be successful after deployment.

**Comment by suvajit-sarkar** [comment]
This is blocked by issue #485

**Comment by himanshulalarya** [comment]
Fabric Network and Frontend pods are up, but it is giving error in API hit using postman.

**Comment by jagpreetsinghsasan** [comment]
It is working.
Tested. Attaching the screenshots for reference

**Comment by jagpreetsinghsasan** [comment]
![image](https://user-images.githubusercontent.com/56861721/78987994-4b0c0a80-7b4d-11ea-861d-63cd109420db.png)

**Comment by jagpreetsinghsasan** [comment]
![image](https://user-images.githubusercontent.com/56861721/78988053-7131aa80-7b4d-11ea-9f9d-f0cbc7cc2458.png)

**Comment by jagpreetsinghsasan** [comment]
The supplychain image URL's need to be changed for the latest dockerhub image builds

**Comment by jagpreetsinghsasan** [comment]
Created a bug for the same #572
