### ISSUE TITLE
Upgrade Fabric Platform code to 1.4.4

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#47]
### Description
As a user I want to use Fabric version 1.4.4 in BAF so that the latest features are available.

### Acceptance Criteria:
1. All Fabric images are upgraded to 1.4.4
2. Ensure backward compatibility of the network in BAF i.e. both 1.4.0 and 1.4.4 should be able to be installed using BAF.

**Comment by sownak** [comment]
Good first issue for anyone who is master in Fabric

**Comment by jagpreetsinghsasan** [comment]
![alpha](https://user-images.githubusercontent.com/56861721/72516324-76959680-3877-11ea-92d9-f7264a945ad4.PNG)
