### ISSUE TITLE
Create crypto material for orion and nodes for the Hyperledger Besu network and IBFT consensus

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#509]
# Description
As a developer I want to create chart which deploys the orion and besu nodes to the kubernetes cluster and uses the IBFT 2.0 consensus.

### 1. Download the besu binary using
------------------------------------
wget https://bintray.com/hyperledger-org/besu-repo/download_file?file_path=besu-1.4.4.tar.gz

### 2. Extract the binary ( the besu binary will be present under besu-1.4.4/bin/besu) using
------------------------------------------------------------------------------------------
tar -zxvf download_file\?file_path\=besu-1.4.4.tar.gz

### 3. Create the ibftConfigFile.json and paste the following content in it (2 is the number of nodes in the blockchain segment)
------------------------------
{
    "genesis": {
      "config": {
         "chainId": 2018,
         "constantinoplefixblock": 0,
         "ibft2": {
           "blockperiodseconds": 2,
           "epochlength": 30000,
           "requesttimeoutseconds": 10
         }
       },
       "nonce": "0x0",
       "timestamp": "0x58ee40ba",
       "gasLimit": "0x47b760",
       "difficulty": "0x1"
    },
    "blockchain": {
      "nodes": {
        "generate": true,
          "count": 2
      }
    }
   }

### 4. Create the genesis block and keys
----------------------------------------
besu-1.4.4/bin/besu  operator generate-blockchain-config --config-file=ibftConfigFile.json --to=crypto --private-key-file-name=key

### 5. Rename nested folders
-------------------------------------------------
Rename the folders inside crypto folder as carrier-bes/carrier  &   manufacturer-bes/manufacturer
The folder structure should look like 

    crypto/keys/carrier-bes/carrier/data/key
    crypto/keys/carrier-bes/carrier/data/key.pub
    crypto/keys/manufacturer-bes/manufacturer/data/key
    crypto/keys/manufacturer-bes/manufacturer/data/key.pub

### 6. Generate the nodeAddress for each node
---------------------------------------------
besu-1.4.4/bin/besu --data-path crypto/carrier-bes/carrier/data public-key export-address --to crypto/carrier-bes/carrier/data/nodeAddress
besu-1.4.4/bin/besu --data-path crypto/manufacturer-bes/manufacturer/data public-key export-address --to crypto/manufacturer-bes/manufacturer/data/nodeAddress

### 7. Put the crypto in the vault
---------------------------------
vault kv put secret/carrier-bes/crypto/carrier/data/key.pub="$(cat crypto/keys/carrier-bes/carrier/data/key.pub)" key="$(cat crypto/keys/carrier-bes/carrier/data/key)"

vault kv put secret/manufacturer-bes/crypto/manufacturer/data/key.pub="$(cat crypto/keys/manufacturer-bes/manufacturer/data/key.pub)" key="$(cat crypto/keys/manufacturer-bes/manufacturer/data/key)"

### 8. Create orion directories
---------------------------------

    crypto/keys/carrier-bes/carrier/orion
    crypto/keys/manufacturer-bes/manufacturer/orion

### 8. Create crypto material for Orion nodes
--------------------------------------------
	a. In each Orion directory, create a file called passwordFile containing a password to encrypt each Orion key pair
	b. In each Orion directory, generate a public/private keypair for the Orion node:
		orion -g nodeKey
	c. Put the passord in the vault:
		vault kv put secret/<namespace>/crypto/<node name>/orion/ passwordFile="$(cat <node name>/orion/passwordFile)" nodeKey.pub="$(cat <node name>/orion/nodeKey.pub)" key.key="$(cat <node name>/orion/nodeKey.key)"
	d. carrier/Orion directory, create a file called orion.conf and add the following properties:
		nodeurl = "http://127.0.0.1:8080/"
		nodeport = 8080
		clienturl = "http://127.0.0.1:8888/"
		clientport = 8888
		publickeys = ["nodeKey.pub"]
		privatekeys = ["nodeKey.key"]
		passwords = "passwordFile"
		tls = "off"
	e. In manufacturer/Orion and warehouse/Orion store/Orion directories, create orion.conf files specifying:
			Different ports
			carrier Orion node as the bootnode (specified by othernodes):
		ex.
			nodeurl = "http://127.0.0.1:8081/"
			nodeport = 8081
			clienturl = "http://127.0.0.1:8889/"
			clientport = 8889
			publickeys = ["nodeKey.pub"]
			privatekeys = ["nodeKey.key"]
			passwords = "passwordFile"
			othernodes = ["http://127.0.0.1:8080/"]
			tls = "off"

Detailed steps for the process described : https://besu.hyperledger.org/en/1.3.3/Tutorials/Privacy/Configuring-Privacy/

### Acceptance Criteria
Corresponding stories to automate the same

**Comment by jagpreetsinghsasan** [comment]
Updated description of the stories
#517 
#518
