### ISSUE TITLE
Automated deployment of Quorum smartcontracts using Ansible

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#520]
### Description
As a developer I want to deploy Quorum smartcontracts using Ansible and truffle so that I can run applications on Quorum

### Acceptance Criteria
1. Reuse truffle and ansible for automated smartcontract deployment
2. Update network.yaml to get smartcontract paths
3. Save the contract address to Vault

**Comment by sownak** [comment]
Was accidentally closed

**Comment by sownak** [comment]
Check this article https://medium.com/coinmonks/ethereum-smart-contract-development-with-a-web-app-part-2-testing-and-deployment-34a885e750b2

**Comment by suvajit-sarkar** [comment]
Updated process for the task -
1. Use Solidity compiler library for Node JS (Solc) to convert the smartcontract to bytecode and its interfaces (Done as part of this issue)
2. Deploy the bytecode onto the nodes using web3 js library (#576 )
3. Get the deployment address (#576)
4. Automate the whole process and store the deployment address in the vault #577
