### ISSUE TITLE
Supplychain image tags needs to be fixed for the .tpl files 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#572]
**Describe the bug**
The image tags are incorrect, thus leading to "ErrImagePull" in the containers of ExpressAPI, Restserver and Frontend deployments.

**To Reproduce**
Deploy the network and then the chaincode to reproduce the bug.

**Expected behavior**
The pods should pull the images and run correctly.

**To Fix**
Changing of image tags (latest/stable) in the .tpl files which will produce output value files with image URL's like
hyperledgerlabs/supplychain_fabric:rest_server_latest
hyperledgerlabs/supplychain_fabric:express_app_latest
index.docker.io/hyperledgerlabs/supplychain_frontend:latest

**Comment by himanshulalarya** [comment]
This bug is already fixed.
Have checked the value files. New Updated tags are coming
