### ISSUE TITLE
Manually deploy the Quorum smartcontract bytecode

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#576]
### Description
As a developer I want to write JS code to manually deploy Quorum smart contract bytecode onto a node

### Acceptance Criteria
1. JS Code to deploy bytecode.
2. Dynamic estimation of gas based on the smart contract to be deployed.
3. Deployed bytecode address as an output value

**Comment by lakshyakumar** [comment]
A javaScript script is written to convert the smart contract at the given path to the bytecode and interface using solc compiler npm-module, The bytecode is then deployed to the quorum node using the rpc port of the quorum node and the address of the deployed contract is returned by the jS script. web3 npm module is used to create the provider and connect and communicate to the rpc port of quorum node.

**Comment by lakshyakumar** [comment]
The Deployed SmartContract is tested on a Quorum Network deployed using Raft consensus and Tessera Transaction manager. The Express APIs tests are performed using postman.

**Comment by lakshyakumar** [comment]
The logic of Estimating the required gas is integrated in the code using the deposit cost and execution cost as calculated by the solc compiler. The execution cost of default 200 iterartions of execution is added which can be increased furthur. The Smart Contract is tested on a Quorum network deployed using the IBFT consensus and Tessera Transaction manager.  The Express APIs tests are performed using postman.

**Comment by lakshyakumar** [comment]
The logic of account unlocking before deployment of smart contract will be added to the js script after we have the locked accounts.
