### ISSUE TITLE
timestamp is returned as null when using RAFT Consensus

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#581]
**Describe the bug**
The "timestamp" values is returned as null when RAFT consensus is used in the Quorum network. When IBFT is used, then there is correct value.

**To Reproduce**
1. Set up a Quorum network using BAF with RAFT consensus (and any transaction manager)
2. Deploy the supplychain smartcontract
3. Start the expressapi service
4. Create a product/container and then fetch the product/container, the timestamp value is null.
5. In history api as well, the time value is null.

**Expected behavior**
The timestamp value should have a datetime value which is the time when the product/container was created.

**Additional context**
This seems to be an issue because of how RAFT handles timestamp. So the smartcontract needs to be updated accordingly.
Ref: https://github.com/jpmorganchase/quorum/issues/190

**Comment by suvajit-sarkar** [comment]
This is resolved

**Comment by srinivasansankaran** [comment]
@suvajit-sarkar I would like to work on it.
