### ISSUE TITLE
Enabling Fabric platform in BAF to support hosting of multiple orderers from multiple organizations for RAFT

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#614]
Adding support of multi organization hosting multi orderers

Some guidance here https://stackoverflow.com/questions/61122349/how-to-add-a-new-orderer-organization-to-existing-hyperledger-fabric-network which has to be automated using helmcharts and ansible

**Comment by davidkhala** [comment]
Now both release-1.4 and release-2.2 see kafka ordererType and fabric-couchdb as deprecated. @sownak Sownak, what is your opinion towards strategy to keep BAF align updates?

**Comment by sownak** [comment]
@davidkhala We already have support for RAFT which can be used instead of Kafka. For replacing couch-db, you can submit enhancement requests. We also plan to add those changes as and when we upgrade to latest Fabric releases.
