### ISSUE TITLE
Add reset-network molecule test scenario in Corda

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#628]
### Description
As a developer I want to run molecule test so that I can test my reset-network roles.

### Acceptance Criteria
1.Molecule tests should cover `delete/gitops_files`, `delete/vault_secrets`, `delete/flux_releases` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by mgCepeda** [comment]
I will be working on this task
