### ISSUE TITLE
Test transaction from newly created organisation node in Fabric network via peer CLI

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#699]
### Description
As a developer I want to add a new organisation to Fabric network and make a transaction from the new organisation peer cli to test it. 

### Acceptance Criteria
1. Output of the transaction done from newly created node

**Comment by himanshulalarya** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/57169320/83400190-0d768000-a420-11ea-83fd-b4aca621131c.png)

Chaincode invoke using the new organization cli.
functions tested: init and create container
Here are the queries
For init:
peer chaincode invoke -o orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt -C allchannel -n supplychain -c '{"Args":["init",""]}'

 

for create container
peer chaincode invoke -o orderer3.hf.dev.aws.blockchaincloudpoc-develop.com:8443 --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt -C allchannel -n supplychain -c '{"Args":["createContainer","{\"misc\":{\"name\":\"Medicine Container\"},\"trackingID\":\"613254c0-5395-4069-971b-fff77dc9c73d\",\"counterparties\":[\"CN=Admin@mh-net,OU=client+OU=mh,O=Mh,L=San Francisco,C=US\"]}"]}'

**Comment by jagpreetsinghsasan** [comment]
for creating container, the correct command is (this should be executed from the manufacturer CLI assuming BAF supplychain chaincode is installed and instantiated) (replace the orderer URL with your orderer URL)
peer chaincode invoke -o ORDERER_URL --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt -C allchannel -n supplychain -c '{"Args":["createContainer","{\"misc\":{\"name\":\"Medicine Container\"},\"trackingID\":\"613254c0-5395-4069-971b-fff77dc9c73d\",\"counterparties\":[\"CN=Admin@mh-net,OU=client+OU=mh,O=Mh,L=San Francisco,C=US\"]}"]}'

**Comment by suvajit-sarkar** [comment]
Reopened based on issue raised on rocket chat

**Comment by jagpreetsinghsasan** [comment]
If you are copying from the above make sure you add the escape sequence.
![alphabeta](https://user-images.githubusercontent.com/56861721/85126590-69783b80-b24b-11ea-91b9-a339ecf0291b.PNG)

**Comment by jagpreetsinghsasan** [comment]
This is tested and it works fine.
