### ISSUE TITLE
Adding new organisation to quorum network is failing

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#702]
**Describe the bug**
Adding new organisation to a exiting quorum network functionality is broken after the latest code merge could be an issue from code merge of PR #698 

**To Reproduce**
1. Deploy a quorum network
2. Deploy adding of new organisation 

**Expected behavior**
The new organisation is added and is discover-able by other nodes

**Comment by himanshulalarya** [comment]
Checked Addition of new Organization on an unlocked network. Working...
![Screenshot (22)](https://user-images.githubusercontent.com/57169320/83865236-8d178e00-a743-11ea-8a52-d15e95bf2012.png)
