### ISSUE TITLE
Add default molecule test scenario in Quorum

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#718]
### Description
As a developer I want to run default molecule test so that I can test my ansible scripts for Quorum.

This is similar to #623 and a similar solution can be applied.

### Acceptance Criteria
1.Molecule tests should cover `create/storageclass`, `setup/vault_kubernetes` and `create/namespace_serviceaccount` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by Dimbu-Afonso** [comment]
Working on this ticket
