### ISSUE TITLE
Add ambassador-certs molecule test scenario in Quorum

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#719]
### Description
As a developer I want to run molecule test so that I can test my `create/certificates/ambassador` role.

### Acceptance Criteria
1.Molecule tests should cover `create/certificates/ambassador` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by angelaalagbe** [comment]
I'll take this issue
