### ISSUE TITLE
Add crypto-constellation molecule test scenario in Quorum

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#723]
### Description
As a developer I want to run molecule test so that I can test my `create/crypto/constellation` role.

### Acceptance Criteria
1.Molecule tests should cover `create/crypto/constellation` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by Dimbu-Afonso** [comment]
Looking into this
