### ISSUE TITLE
Add tessera molecule test scenario in Quorum

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#724]
### Description
As a developer I want to run molecule test so that I can test my `create/tessera` role.

### Acceptance Criteria
1.Molecule tests should cover `create/tessera` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by angelaalagbe** [comment]
I'll take this issue

**Comment by mgCepeda** [comment]
I am working on this issue
