### ISSUE TITLE
Add Fabric molecule tests in github actions

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#733]
### Description
As a developer I want to run all Fabric Molecule test Scenarios so that the Github Actions CI script is complete for Fabric.
Add a condition so that the Fabric tests are run only when the check-in has a "[fabric]" in the commit message

### Acceptance Criteria
1. Github Actions CI test should run for Fabric when commit message has "[fabric]"
2. All Fabric molecule test scenarios should be run

**Comment by TonyRowntree** [comment]
I am taking this
