### ISSUE TITLE
Add Fabric chaincode static tests in Github Actions

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#739]
### Description
As a developer I want to run Fabric chaincode static tests so that the Github Actions CI script is complete for Fabric.
Add a condition so that the chaincode tests are run only when the check-in has a "[fabric]" in the commit message

### Acceptance Criteria
1. Github Actions CI test should run static chaincode tests when commit message has "[fabric]"

**Comment by Dimbu-Afonso** [comment]
Looking at this
