### ISSUE TITLE
Add Quorum smartcontract static tests in GitActions

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#740]
### Description
As a developer I want to run Quorum smartcontract static tests so that the Git Actions script is complete for Quorum.
Add a condition so that the smartcontract tests are run only when the check-in has a "[quorum]" in the PR message

### Acceptance Criteria
1. Git Actions test should run static smartcontract tests when commit message has "[quorum]"

**Comment by pppazos** [comment]
I can work this one
