### ISSUE TITLE
Add Corda image build in Git Actions

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#741]
### Description
As a developer I want to build Corda image for a specific corda version and tag it according to BAF release number, so that all build commands are available as code.
Now the corda image is built from Docker hub automated build where it does not accept Build version.

### Acceptance Criteria
1. Correct corda image build is available on dockerhub
2. Git Action succeeds

**Comment by pppazos** [comment]
I can work this if needed
