### ISSUE TITLE
Add baf-build image build in Git Actions

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#743]
### Description
As a developer I want to build baf-build image and tag it according to BAF release number, so that all build commands are available as code.

### Acceptance Criteria
1. Correct baf-build image build is available on dockerhub
2. GitAction succeeds

**Comment by Roshan13046** [comment]
I would like to work on this good first issue. Please suggest how to proceed to fix the issue. 
Where can I find the folder or file location?

**Comment by Roshan13046** [comment]
The changes are to be done in the config.yml file of circleci folder, isn't it?

**Comment by sownak** [comment]
This is not about creating a custom image for Circle CI, this is about creating the docker build from circle ci build so that we can tag the https://hub.docker.com/r/hyperledgerlabs/baf-build/tags?page=1&ordering=last_updated with release numbers

**Comment by pppazos** [comment]
I can work this if needed
