### ISSUE TITLE
Update HAProxy to the latest stable version

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#760]
### Description
As a developer I want to use the latest stable version of HAProxy to avoid any vulnerabilities 

### Acceptance Criteria
1. Test fabric network deployment using HAProxy

**Comment by sownak** [comment]
Upgrading to HAProxy-ingress controller version v0.9.1. which is the latest stable release from https://github.com/jcmoraisjr/haproxy-ingress/releases
