### ISSUE TITLE
Some of the links in the readthedocs are broken

### ISSUE THREAD

**Issue by deepakkumardbd** [hyperledger-labs/blockchain-automation-framework#773]
**Describe the bug**
https://blockchain-automation-framework.readthedocs.io/en/latest/operations/setting_dlt.html
The links are broken for "Guidance Here" across steps 2 ,3 , 4 and 6.

**To Reproduce**
1. Go to https://blockchain-automation-framework.readthedocs.io/en/latest/operations/setting_dlt.html
2. Click on "Guidance Here" link.

**Expected behavior**
The link should open to the given reference

**Comment by suvajit-sarkar** [comment]
bug raised based on rocket chat report thread :
https://chat.hyperledger.org/channel/blockchain-automation-framework?msg=ZMXpna4kk78GGDCyB

**Comment by sillysachin** [comment]
NOTE: Please follow these "instructions" link broken in page https://blockchain-automation-framework.readthedocs.io/en/develop/operations/fabric_networkyaml.html
