### ISSUE TITLE
Helm upgrade: Upgrade/Remove Helm and Tiller

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#856]
### Description
As a developer I want to upgrade helm installation to helm3 and remove all tiller references from the shared platform
#### To be removed/modified:
platforms/shared/configuration/roles/setup/tiller
platforms/shared/configuration/molecule/default
platforms/shared/configuration/molecule/kubernetes-corda
platforms/shared/configuration/molecule/kubernetes-fabric
platforms/shared/configuration/molecule/kubernetes-indy

#### To modify/add:
platforms/shared/configuration/roles/setup/helm

### Acceptance Criteria
1. All tiller references are removed
2. Helm installation should be changed to v3.2.4

**Comment by suvajit-sarkar** [comment]
Closed with the PR #929
