### ISSUE TITLE
Incorrect sample network-quorum.yaml file

### ISSUE THREAD

**Issue by Pramod-Somanchi** [hyperledger-labs/blockchain-automation-framework#860]
**Describe the bug**
The sample network-quorum.yaml file contains both quorum and corda values as external_url_suffix in multiple places. For ex- In warehouse organization below value is present:-
external_url_suffix: test.corda.blockchaincloudpoc.com

**To Reproduce**
1. Go to "blockchain-automation-framework/platforms/quorum/configuration/samples/network-quorum.yaml
2. Click on network-quorum.yaml
3. Scroll down to line no.122 i.e organization name: manufacturer, line no. 176 i.e organization name: store and line no. 230 i.e organization name: warehouse.
4. See error - external_url_suffix: test.corda.blockchaincloudpoc.com

**Expected behavior**
It should have below value:-
external_url_suffix: test.quorum.blockchaincloudpoc.com

**Screenshots**
![image](https://user-images.githubusercontent.com/68386537/87948575-8316d800-cac2-11ea-8740-287e3caa4666.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**
N/A

**Comment by sownak** [comment]
Please explain why it is a bug i.e. what was the issue that you faced because of this.
Different clusters may have different suffixes. And this is a sample.

**Comment by Pramod-Somanchi** [comment]
HI Sownak,

Actually in the file the example values should be consistent so that it can be easy for a newbie to understand the yaml and replace the values accordingly. Here in this case few sample values are referring as corda and few as quorum which was causing the confusion.

Thanks,
Somanchi Pramod
