### ISSUE TITLE
Docker build fails while creating custom agent for Aries

### ISSUE THREAD

**Issue by shubhadeep-acn** [hyperledger-labs/blockchain-automation-framework#866]
**Describe the bug**
We have deployed the BAF framework and wanted to deploy Indentity-App by referring the documentation https://github.com/hyperledger-labs/blockchain-automation-framework/tree/master/examples/identity-app
We were unable to create Custom Aries Image 

**To Reproduce**
1. Go to Link https://github.com/hyperledger-labs/blockchain-automation-framework/tree/master/examples/identity-app

2. Click on Step 2 [Documentation](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/master/examples/identity-app/images/agents/README.md) Link
We are able to create base Image but when we trigger 
3. Refer Docker Build step in  'Build a custom image'
`[00:26] Sengupta, Shubhadeep
    I get following error when I run from path 

/project/blockchain-automation-framework/examples/identity-app/images/agents
docker build -t aries-agents .

We could see below error
❯ docker build -t aries-agents .
Sending build context to Docker daemon  44.54MB
Step 1/4 : FROM hyperledgerlabs/faber-alice-demo:1.11.0
pull access denied for hyperledgerlabs/faber-alice-demo, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
`
**Expected behavior**
Custom Docker Image should be build  without any error.

**Workaround/Fix**
I have updated the fix by replacing the  base docker which was FROM hyperledgerlabs/faber-alice-demo:1.11.0. to my own custom created Image which was part of **Build a base image**. step and I was able to create Custom Image

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by sauveergoel** [comment]
The error you getting is related to configuring your docker hub account credentials in your execution env.

**Comment by shubhadeep-acn** [comment]
I have logged in using my own Docker Hub Credentials , attaching screenshot & my own image which worked  ( which is pulled from) https://hub.docker.com/repository/docker/shubhadeep14/faber-alice-demo. or my local repo 

![image](https://user-images.githubusercontent.com/68507510/88172446-a070b100-cc3e-11ea-9d0e-b2fc723e9000.png)

**Comment by sauveergoel** [comment]
This issue is already catered in the develop branch
