### ISSUE TITLE
Use only the private key in gitops rather than configuring both the password and the private key

### ISSUE THREAD

**Issue by sivaramsk** [hyperledger-labs/blockchain-automation-framework#876]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In git-ops configuration, users configure the private_key which has write access to the repo. Why not use the private_key itself rather than requiring the user to configure the password as well. 

Changes needed:
1. Update the ansible role `platforms/shared/configuration/roles/git_push` to use git ssh given a choice. (add a choice parameter in network yaml)
2. The changes should not break existing code i.e. current set-up of using https should also exist and work as it does now.
3. Use the private_key from network.yaml for authentication.
4. Test the complete set-up of at least one platform.

**Comment by sownak** [comment]
Feature request to enable git_push using SSH rather than https, as the private key is already supplied.

**Comment by blockchainmonk** [comment]
i'll be happy to support if there is guide to get me started here. I am good with Hyperledger Fabric and have some experience with Corda too.

**Comment by sownak** [comment]
@blockchainmonk This task is more about Ansible and git than Fabric/Corda. The ansible role `platforms/shared/configuration/roles/git_push` uses git https to checkin; In this task this needs to be changed to use ssh and the given ssh key. 
I have updated the main description as well.
