### ISSUE TITLE
Manually deploy Enterprise Corda Nodes

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#878]
### Description
As a developer, I want to manually deploy Corda Enterprise 4.4 nodes, so that I can test if the the Bridge and Float can connect to the network.

### Prerequisites
1. Working charts for the rest of the CENM services
2. Use the CENM service deployed by BAF

### Acceptance Criteria
1. CENM service used should be deployed using BAF charts
2. Peer-to-peer communication should be working
3. Float should be able to connect to Node
4. Node should be able to connect to Bridge

**Comment by lakshyakumar** [comment]
getting method not enabled error message when following the besu documentation for deploying the smart contract on Besu node. used web3.eea.sendRawTransaction(contractOptions) function  to deploy the smart contract, web3-eea is a web3 wrapper library.
Initiated the chat in Besu-contributor Rocket chat to get an idea for the error messages.

**Comment by lakshyakumar** [comment]
The `alloc` section in `ibftConfigFile.json` file is empty in BAF code, The section should be populated by the pre generated 
 `eth_accounts`. Empty `alloc` section is causing the error messages in the besu APIs while trying to deploy the smartcontracts.
Posted a question to the Besu-contributor rocket chat about the guide to generate the `eth_account` for besu network.

**Comment by lakshyakumar** [comment]
Setup the example IBFT Orion Besu network, and deployed the `signed smart contract binary` on the running besu network using the `web3-eaa` library.

**Comment by lakshyakumar** [comment]
We have to add the logic of populating the `alloc` section of `ibftConfigFile.json` file to the BAF code with `eth_accounts`. The ethereum accounts can either be generated or can be taken from `network.yam` config file. We can write the javascript code to deploy the smart contract on Besu network using the `web3-eea` library after converting it to the binary contract format using `solidity` library.

**Comment by suvajit-sarkar** [comment]
The manual deployment works, issue #933 is created to make changes in float and bridge from the finding of this story
