### ISSUE TITLE
Document the successful BAF Corda network verification steps

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#883]
### Description
As a operator I want to have a documented BAF Corda network verification guide, calling out various steps to confirm the successful network deployment using BAF.

### Acceptance Criteria
1. A Page under operations guide: "Verify that Corda DLT network is working"

**Comment by jwavoetacn** [comment]
**Verify that the R3-Corda network is working**

1. You need to verify that the network is successfully configured as mentioned in setting_dlt.md.
2. Check if all nodes are running: kubectl get pods -A
3. Verify that all the nodes are shown in the network map by going to the URL specified in the network.yaml.
4. Check Corda status: kubectl logs <podname> -n <namespace> -c corda-node
5. Check Corda logging: kubectl logs <podname> -n <namespace> -c corda-logs

Adding the above instructions to a new .md file including with screenshots and/or output.

**Comment by jwavoetacn** [comment]
Please review this file: https://github.com/jwavoetacn/blockchain-automation-framework/blob/feature/883-r3-corda-checks/docs/source/operations/baf_verify.md
