### ISSUE TITLE
Document the successful BAF Quorum network verification steps

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#884]
### Description
As a operator I want to have a documented BAF Quorum network verification guide, calling out various steps to confirm the successful network deployment using BAF.

### Acceptance Criteria
1. A Page under operations guide: "Verify that Quorum DLT network is working"

**Comment by srinivasansankaran** [comment]
I would like to work on this @suvajit-sarkar
