### ISSUE TITLE
Upgrade the Fabric channel capability to version 2.0

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#886]
### Description
As a developer i want to upgrade channel capability to version 2.0 for Fabric 2.0 network 

### Acceptance Criteria
1. Test Fabric network 2.0 successfully

**Comment by himanshulalarya** [comment]
Upgrade channel capabilities for Fabric network for version 2.0, here 
https://github.com/hyperledger-labs/blockchain-automation-framework/blob/master/platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxinit.tpl
Take the reference from:
https://hyperledger-fabric.readthedocs.io/en/release-2.0/capabilities_concept.html
