### ISSUE TITLE
Tessera 0.11 version is not working

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#900]
**Describe the bug**
Tessera 0.11 version with Quorum is not working.

**To Reproduce**
1. Deploy a Quorum network with RAFT or IBFT consensus and TM as tessera 0.11
2. The pods do not start as tessera:0.11 image is not found

**Expected behavior**
It seems that tessera 0.11 was not an official release, so all references to tessera 0.11 needs to be updated to 0.10.4 (0.10.6 is the latest release, but we are going to use an older and hopefully more stable release).
Then quorum network should be tested for both RAFT and IBFT.

Official tessera releases https://github.com/jpmorganchase/tessera/releases

**Comment by sownak** [comment]
The JDK version for both baf-build latest and jenkins tags needs to be updated to 14 for tessera to work. This means all platforms have to be tested with jdk 14

**Comment by suvajit-sarkar** [comment]
Tested the BAF quorum deployment with tessera 0.10.4, the deployment works with JDK version 14 doesn't work with Java8
The tessera 0.11 image is still available works with Java 8
![tessera 0 11](https://user-images.githubusercontent.com/55580532/91030586-06c16880-e61d-11ea-8648-8b2381821038.png)

**Comment by suvajit-sarkar** [comment]
For tessera 0.10.4 we have tested using JAVA 14, which would be now our JAVA version upgrade for all platforms 
Reference story #965
