### ISSUE TITLE
Quorum re-deployment fails

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#905]
**Describe the bug**
The BAF Quorum deployment is not idempotent, it fails when running the deployment again without resetting.

**To Reproduce**
1. Deploy a quorum network successfully using BAF.
2. After all the nodes are up, redeploy using the same network.yaml
3. The deployment fails with the following error
TASK [Get root certs] **********************************************************

TASK [/jenkins/workspace/BAF_Demo_multi_quorum-GNPANTIXFAVEYAQB6ZDJIEMQ5GAEN2YJXF6UPSXDSZK7S6PPOAGQ/platforms/quorum/configuration/roles/setup/get_crypto : Ensure directory exists] ***
ok: [localhost]
TASK [/jenkins/workspace/BAF_Demo_multi_quorum-GNPANTIXFAVEYAQB6ZDJIEMQ5GAEN2YJXF6UPSXDSZK7S6PPOAGQ/platforms/quorum/configuration/roles/setup/get_crypto : Save cert] ***
skipping: [localhost]

TASK [/jenkins/workspace/BAF_Demo_multi_quorum-GNPANTIXFAVEYAQB6ZDJIEMQ5GAEN2YJXF6UPSXDSZK7S6PPOAGQ/platforms/quorum/configuration/roles/setup/get_crypto : Save key] ***
skipping: [localhost]

TASK [/jenkins/workspace/BAF_Demo_multi_quorum-GNPANTIXFAVEYAQB6ZDJIEMQ5GAEN2YJXF6UPSXDSZK7S6PPOAGQ/platforms/quorum/configuration/roles/setup/get_crypto : Save root keychain] ***
changed: [localhost]

TASK [/jenkins/workspace/BAF_Demo_multi_quorum-GNPANTIXFAVEYAQB6ZDJIEMQ5GAEN2YJXF6UPSXDSZK7S6PPOAGQ/platforms/quorum/configuration/roles/setup/get_crypto : Extracting root certificate from .jks] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cd /jenkins/workspace/BAF_Demo_multi_quorum-GNPANTIXFAVEYAQB6ZDJIEMQ5GAEN2YJXF6UPSXDSZK7S6PPOAGQ/platforms/quorum/configuration/build/quorumrootca\neval \"keytool -importkeystore -srckeystore rootca.jks -destkeystore rootca.p12 -srcalias rootca -srcstoretype jks -deststoretype pkcs12 -srcstorepass 'quorum' -deststorepass 'quorum'\"\neval \"openssl pkcs12 -in rootca.p12 -nokeys -out rootca.pem -passin pass:'quorum' -passout pass:'quorum'\"\neval \"openssl pkcs12 -in rootca.p12 -nodes -nocerts -out rootca.key -passin pass:'quorum' -passout pass:'quorum'\"\n", "delta": "0:00:00.619777", "end": "2020-08-06 11:43:02.891785", "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 11:43:02.272008", "stderr": "Importing keystore rootca.jks to rootca.p12...\npkcs12: Cannot open input file rootca.p12, No such file or directory\npkcs12: Use -help for summary.\npkcs12: Cannot open input file rootca.p12, No such file or directory\npkcs12: Use -help for summary.", "stderr_lines": ["Importing keystore rootca.jks to rootca.p12...", "pkcs12: Cannot open input file rootca.p12, No such file or directory", "pkcs12: Use -help for summary.", "pkcs12: Cannot open input file rootca.p12, No such file or directory", "pkcs12: Use -help for summary."], "stdout": "keytool error: java.lang.Exception: Alias <rootca> does not exist", "stdout_lines": ["keytool error: java.lang.Exception: Alias <rootca> does not exist"]}

**Expected behavior**
The deployment should not fail. It should succeed even when there is nothing to change.

**Comment by suvajit-sarkar** [comment]
is this still a valid bug ?

**Comment by azoumi** [comment]
@suvajit-sarkar This is still valid. Will apply same fix as with besu. Adding the needed files to the vault and checking before deployment if its there before recreating.
