### ISSUE TITLE
Travis CI Build Failing

### ISSUE THREAD

**Issue by himanshulalarya** [hyperledger-labs/blockchain-automation-framework#918]
**Describe the bug**
Build Fail for Travis CI.
**To Reproduce**
1. Login travis-ci with github and grant access to your repo.
2. Run the build Job
3. Check the logs status 
4. See error "docker.errors.APIError: 400 Client Error: Bad Request ("client version 1.39 is too new. Maximum supported API version is 1.38")"

**Comment by sownak** [comment]
This bug description is not of correct template. Please use the BAF bug template to create a bug.
