### ISSUE TITLE
Enabling Continous deployment (CD) for Hyperledger fabric using Spinnaker

### ISSUE THREAD

**Issue by sanusatyadarshi** [hyperledger-labs/blockchain-automation-framework#921]
**Is your feature request related to a problem? Please describe.**
Running all the kubectl commands can get repetitive and prone to errors. If we use a tool to deploy the helm charts and k8s manifests using a deployment tool, it will improve the developer workflow.

**Describe the solution you'd like**

Have Continous Deployment pipelines setup using spinnaker(or any other open-source tool) which deploys the Hyperledger Fabric Network on Kubernetes

**Comment by sownak** [comment]
@sanusatyadarshi Thanks a lot for this feature request. Could you please clean up the description to be a bit more detailed? And remove the line "A clear and concise.... ", these are for example/guidance only.

**Comment by sanusatyadarshi** [comment]
Sure.

**Comment by sownak** [comment]
Thanks. We do use Weaveworks Flux and Ansible so that no kubectl commands are run. If you are going to work on Spinnaker, it will be great if you can add a comparison between Spinnaker and Flux/Ansible.

**Comment by sanusatyadarshi** [comment]
Sure. I have not used Weaveworks Flux. I have used Ansible but more for configuration management of servers and not as a deployment tool. So I will spend some time to create a comparison between them. 
Thanks

**Comment by sownak** [comment]
@sanusatyadarshi  Are you progressing on this? Otherwise we will be closing the issue as `wontfix`

**Comment by sownak** [comment]
Closing this issue as stale. Please re-open if needed.
