### ISSUE TITLE
Automation of deployment of smart contract using the ansible

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#940]
### Description

As a developer i want to automate the deployment of smartcontracts on Besu using the signed transactions and deploy.js code.

### Acceptance Criteria
1. Able to deploy the smartcontract on tls-disabled Besu org node using Ansible playbook

**Comment by jagpreetsinghsasan** [comment]
This issue is currently blocked by https://github.com/hyperledger-labs/blockchain-automation-framework/issues/999
Once the dependent issue is fixed, this issue can be picked up
