### ISSUE TITLE
Enable an option to turn off firewall 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-labs/blockchain-automation-framework#945]
Currently the firewall option to disable it, is not available

The feature which unlinks the float and bridge from deployment based on a condition, and decouples the node from firewall is needed. 
Useful links:
https://docs.corda.net/docs/corda-os/4.5/key-concepts-node.html
https://docs.corda.net/docs/cenm/1.2.html

**Comment by jwavoetacn** [comment]
- Added: `when: peer.firewall.enabled = true` to "float/tasks/main.yaml" and bridge/tasks/main.yaml
- Added the firewall value fields to "/node/values.yaml"

**Comment by jwavoetacn** [comment]
Waiting for #804 which makes it easier to automatically deploy and test the firewall
