### ISSUE TITLE
Corda opensource deployment fails

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#948]
**Describe the bug**
Corda opensource deployment is failing with error "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'notarydb'\n\nThe error appears to be in '/jenkins/workspace/BAF_Demo_multi_corda-O3T5W4AECDXUDF45YR3WKGXEAJD2XJJI5CJXGBQLH75X73B63UJA/platforms/shared/configuration/roles/helm_lint/tasks/main.yaml'

**To Reproduce**
1. Deploy a corda network
2. notarydb helm lint fails

**Expected behavior**
Helm lint should pass and corda network should be deployed.

**Additional context**
The following diff is the root cause of the problems. Any change in shared should take care of impact on existing code
![image](https://user-images.githubusercontent.com/20537268/90499172-1fbfaa80-e141-11ea-8a2a-717864304f58.png)

**Comment by jwavoetacn** [comment]
Below the concept body for the 'corda_network_verify.md':

# Verify that the R3-Corda network is working
1. You need to verify that the network is successfully configured as mentioned in [setting_dlt.md](./setting_dlt.md).

2. Check if all* pods are running: 
**Keep in mind that pods are still initializing after Ansibel is finished.*
`kubectl get pods -A`
![Pods overview](<file location>)

3. Verify that all* the nodes are shown in the network map by going to the URL specified in the network.yaml.
**Keep in mind that pods (nodes) are still initializing after Ansibel is finished.*
`command`
![Network map](<file location>)

4. Check registration of Corda:
`kubectl logs <podname> -n <namespace> node-initial-registration`
![Corda registration](<file location>)

5. Check corda logging: 
`kubectl logs <podname> -n <namespace> -c corda-logs`
![Corda logging](<file location>)

6. Check Corda status: 
`kubectl logs <podname> -n <namespace> -c corda-node`
![Corda status](<file location>)

7. Check DB pods:
`command`
![DB status](<file location>)
