### ISSUE TITLE
Upgrade the Quorum platform code for Helm3

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#950]
### Description
As a developer I want to add helm3 related code for Quorum network so that the deployment is deployed & cleaned properly.

Please refer to PR #1035 which contains similar change for Quorum (Tessera specific).

Steps:
1. Take latest code from feature/helm3 branch
2. Run the Quorum network, ensuring that helm3 is installed
3. Update the reset network code
4. Run reset network and verify all deployment components are deleted

### Acceptance Criteria
1. Running reset network resets the whole network deployments
2. Testing for all 2 possible combination of Constellation + consensus of Quorum:
- Raft + Constellation 
- IBFT + Constellation
3. The cluster after reset, should work with helm2 (no CRD's should be left after cleanup)

**Comment by abevers** [comment]
`4. Application charts (examples/supplychain-app/charts) should also be ugraded to have end-to-end testing of the platform.`

=> The upgradation of the application code has been moved to a seperate issue.
