### ISSUE TITLE
Networkmap changes to implement latest nms chart.

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#96]
### Description
1) changes in nms.tpl ,networkmap chart and implement them to get nms up and running using the latest BLOI networkMap chart (available in BLOI feature/ambassador branch - https://innersource.accenture.com/projects/BLOI/repos/platform-kubernetes-corda/browse/charts/networkMap) . 

2) certificate creation for ssl communication with mongodb database.

### Acceptance Criteria
1) Existing functionality should not hamper
2) Value and chart file should pass the helm lint without error.
3) Creation of mongodb certificate authority(if not catered at doorman level)
4) Certificate creation for mongodb server of nms and putting them into vault
5) nms should be up and running.
6) Playbook should run from ansible cli and complete network should be up and running from ansible cli too.
7) Update the doc to reflect the changes made

**Comment by sownak** [comment]
Closed as per #217
