### ISSUE TITLE
Java Chaincode Support for Hyperledger Fabric in BAF

### ISSUE THREAD

**Issue by himanshulalarya** [hyperledger-labs/blockchain-automation-framework#966]
**Is your feature request related to a problem? Please describe.**
Enable Java Chaincode support for Hyperledger Fabric in BAF.
Update the chaincode section to provide support for Java based chaincode for BAF fabric network.

**Comment by sownak** [comment]
@himanshulalarya Please elaborate what changes are needed for Java chaincode support.
