### ISSUE TITLE
Implement AnchorPeers in Fabric

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#97]
### Description
AnchorPeers need to be implemented in Fabric so that the Supplychain App can work.
Now, the fabric-restserver fails to send messages to other participants in the channel.

**Comment by jagpreetsinghsasan** [comment]
The Common Name in subject can be only be of 64 characters long by default
https://tools.ietf.org/html/rfc5280
ub-common-name INTEGER ::= 64

**Comment by sownak** [comment]
Closed by #157 
The issue was that Ambassador was not performing ssl-passthrough and hence certificates of peers were not validated while setting up anchor peers. This has been solved by use HAProxy which does ssl-passthourgh
