### ISSUE TITLE
Enable DNS support in Besu

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#983]
### Description
As a developer I want to use DNS names instead of IP addresses so that I can build a more production worthy network with Hyperledger Besu.
1. Hyperledger Besu 1.5.3 must be used as this adds the DNS support https://github.com/hyperledger/besu/releases/tag/1.5.3
2. Check https://github.com/hyperledger/besu/pull/1247 for usage
3. Do not use AWS NLB while setting up ambassador while testing
4. remove static IP addresses from Besu network.yaml

### Acceptance Criteria
1. NLB is not created for Ambassador, instead Classic LB is created.
2. Besu nework is able to start-up.
3. Smartcontract is deployed manually

**Comment by jagpreetsinghsasan** [comment]
This is on hold, till the HL Besu comes up with 1.5.3 upgrade

**Comment by ragalz** [comment]
I'll take on this one
