### ISSUE TITLE
Integrate Ambassador proxy certificates with PKI-tool certificates for Corda Enterprise

### ISSUE THREAD

**Issue by sownak** [hyperledger-labs/blockchain-automation-framework#996]
### Description
As a developer I want to generate/integrate the Ambassador proxy certificates using PKI-tool so that the Ambassador proxy uses the certificates generated from the same certification authority as the Corda Nodes.

1. Explore how pki generator can be used to create Ambassador certificates with the public domain names like idman.xx.domain.com etc.
2. This will ensure the ambassador certificates are in the truststore already, hence we do not need to add them via `keytool -importcert -file ${BASE_DIR}/certificates/networkmap.crt ...` commands
3. `platforms/corda-ent/configuration/roles/create/certificates/cenm/tasks/main.yaml` need to be modified to extract the cert and key from keystore and update the kubernetes secret for ambassador
4. Then we do not need root access for the docker images of networkmap, notary and node.

### Acceptance Criteria
1. Ambassador certificates are generated using pki-generator and not openssl
2. No "keytool -importcert -file ${BASE_DIR}/certificates/networkmap.crt .." commands in charts
3. Notary and Networkmap is updated without any error.
4. Notary and Nodes are visible when the following is called
- curl -k https://nmap-public-uri:8443/network-map-user/node-infos
- curl -k https://nmap-public-uri:8443/network-map-user/network-map

**Comment by sownak** [comment]
@jagpreetsinghsasan  this is the issue to remove openssl certs from Corda-enterprise

**Comment by pppazos** [comment]
working on this
