### ISSUE TITLE
SmartContracts deployments are failing over the member node in besu network

### ISSUE THREAD

**Issue by lakshyakumar** [hyperledger-labs/blockchain-automation-framework#999]
**Describe the bug**
Smart contracts are only deployed on besu node with the address that are added to the RLP encoded string in `extraData` in `genesis.json`, i.e., the validator nodes. smartcontract deployments are failing on member nodes in besu.

**To Reproduce**
1. Edit the besu network.yaml
2. Edit the crypto generation of IBFT consensus
3. Modify the role `Get node data` from `main.yaml` role of `blockchain-automation-framework/platforms/hyperledger-besu/configuration/roles/create/crypto/ibft`
4. Try to deploy the smart contract over one of the member node.
`
**Expected behavior**
SmartContract should be deployed over the member node.

**Comment by lakshyakumar** [comment]
Chat link for the possible causes and direction.
https://chat.hyperledger.org/channel/besu-contributors?msg=jzYcYWNrz8BJvxgBk

**Comment by azoumi** [comment]
Fixed with PR #1048 It seems like that the minimum gasprice was the issue. As we are not using gas for contract deployment it can be set to 0 so we don't need to give member nodes wei to deploy contracts.
